export async function prepareImage(file:File,maxDimension=1600,quality=.82){
  if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('รองรับเฉพาะ JPG, PNG หรือ WebP')
  const bitmap=await createImageBitmap(file);const scale=Math.min(1,maxDimension/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');if(!context)throw new Error('ไม่สามารถประมวลผลรูปภาพได้');context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('บีบอัดรูปภาพไม่สำเร็จ')),'image/webp',quality));const base64=await blobToBase64(blob);return{fileName:file.name.replace(/\.[^.]+$/,'.webp'),mimeType:'image/webp',base64,preview:URL.createObjectURL(blob),size:blob.size}
}
export async function prepareLogo(file:File,maxDimension=1200){
  if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('รองรับเฉพาะ JPG, PNG หรือ WebP')
  const bitmap=await createImageBitmap(file);const scale=Math.min(1,maxDimension/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');if(!context)throw new Error('ไม่สามารถประมวลผลรูปภาพได้');context.clearRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const mimeType=file.type==='image/png'?'image/png':'image/webp';const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('ประมวลผลโลโก้ไม่สำเร็จ')),mimeType,.88));const base64=await blobToBase64(blob);const extension=mimeType==='image/png'?'.png':'.webp';return{fileName:file.name.replace(/\.[^.]+$/,extension),mimeType,base64,preview:URL.createObjectURL(blob),size:blob.size}
}
function blobToBase64(blob:Blob){return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]||'');reader.onerror=()=>reject(new Error('อ่านรูปภาพไม่สำเร็จ'));reader.readAsDataURL(blob)})}
