import { useEffect, useState } from 'react'
import { Bell, CheckCircle, Circle, Gear, Heart, Package, SignOut, SpinnerGap, Star, Timer, UserCircle } from '@phosphor-icons/react'
import type { ApiClient } from '../api/client'
import type { Locale, OrderSummary, SessionInfo, ThemePreference, UserNotification } from '../domain/types'

const text = (locale: Locale, th: string, en: string) => locale === 'th' ? th : en
export function LegacyOrdersPage({ locale, session, api, demo, pendingOrder, onPay }: { locale: Locale; session: SessionInfo | null; api: ApiClient | null; demo: boolean; pendingOrder: OrderSummary | null; onPay: (order: OrderSummary) => void }) {
  const [orders, setOrders] = useState<OrderSummary[]>(pendingOrder ? [pendingOrder] : []); const [error, setError] = useState('');const [loading,setLoading]=useState(Boolean(!demo&&api&&session))
  useEffect(() => { if (!demo && api && session){setLoading(true);api.listOrders(session.token).then(setOrders).catch((cause) => setError(cause instanceof Error ? cause.message : 'โหลดออเดอร์ไม่สำเร็จ')).finally(()=>setLoading(false))}else setLoading(false) }, [api, session, demo])
  if(loading)return <div className="page narrow-page"><section className="content-loading" aria-live="polite" aria-busy="true"><SpinnerGap className="spin" size={28}/><strong>{text(locale,'กำลังโหลดคำสั่งซื้อ…','Loading your orders…')}</strong><div className="skeleton-lines" aria-hidden="true"><i/><i/><i/></div></section></div>
  return <div className="page narrow-page"><div className="section-heading"><div><h1>{text(locale, 'คำสั่งซื้อของฉัน', 'My orders')}</h1><p>{text(locale, 'ดูการชำระเงิน ข้อความจากร้าน และสถานะล่าสุด', 'See payments, store messages, and current status.')}</p></div></div>{error && <p className="form-error">{error}</p>}{orders.length === 0 ? <div className="empty-state"><Package size={38} /><h2>{text(locale, 'ยังไม่มีคำสั่งซื้อ', 'No orders yet')}</h2><p>{text(locale, 'ออเดอร์ที่ยืนยันแล้วจะปรากฏที่นี่', 'Confirmed orders will appear here.')}</p></div> : <div className="order-list">{orders.map((order) => <article className="order-card" key={order.id}><div><span>{order.orderType === 'PREORDER' ? 'Pre-order' : text(locale, 'พร้อมส่ง', 'Ready stock')}</span><strong>{order.reference}</strong></div><span className="status-badge">{order.status === 'AWAITING_PAYMENT' ? text(locale, 'รอส่งหลักฐาน', 'Awaiting proof') : order.status === 'BALANCE_DUE' ? text(locale,'รอชำระยอดคงเหลือ','Balance due') : order.status}</span><dl><div><dt>{text(locale, 'ยอดรวม', 'Total')}</dt><dd>฿{(order.subtotal+(order.shippingFee||0)).toLocaleString()}</dd></div><div><dt>{text(locale, 'ชำระแล้ว', 'Paid')}</dt><dd>฿{order.totalPaid.toLocaleString()}</dd></div><div><dt>{text(locale, 'คงเหลือ', 'Balance')}</dt><dd>฿{order.balanceDue.toLocaleString()}</dd></div></dl>{order.items&&<div className="order-items">{order.items.map(item=><span key={item.id}>{item.titleSnapshot} × {item.quantity}</span>)}</div>}{order.history&&<details className="order-timeline"><summary>{text(locale,'ประวัติสถานะ','Status history')}</summary>{order.history.map(row=><div key={row.id}><strong>{row.toStatus}</strong><span>{new Date(row.createdAt).toLocaleString(locale==='th'?'th-TH':'en-US')}{row.note?` · ${row.note}`:''}</span></div>)}</details>}{order.messages?.map(message=><p className="order-message" key={message.id}><strong>{text(locale,message.titleTh,message.titleEn)}</strong><br/>{text(locale,message.bodyTh,message.bodyEn)}</p>)}{['AWAITING_PAYMENT','BALANCE_DUE'].includes(order.status)&&<button className="primary-button" onClick={()=>onPay(order)}>{text(locale,order.status==='BALANCE_DUE'?'ชำระยอดคงเหลือ':'ส่งหลักฐานการโอน',order.status==='BALANCE_DUE'?'Pay balance':'Submit payment proof')}</button>}</article>)}</div>}</div>
}

const customerStatus:Record<string,{th:string;en:string}>={AWAITING_PAYMENT:{th:'รอส่งหลักฐานการชำระเงิน',en:'Awaiting payment proof'},PAYMENT_REVIEW:{th:'รอตรวจสอบการชำระเงิน',en:'Payment review'},PAYMENT_CONFIRMED:{th:'ยืนยันการชำระเงินแล้ว',en:'Payment confirmed'},PAYMENT_REJECTED:{th:'หลักฐานการชำระเงินไม่ผ่าน',en:'Payment proof rejected'},SELLER_PROCESSING:{th:'รอผู้ขายจัดส่ง',en:'Waiting for seller'},SELLER_PREPARING_SHIPMENT:{th:'ผู้ขายเตรียมจัดส่ง',en:'Seller preparing shipment'},SELLER_SHIPPED:{th:'ผู้ขายส่งของแล้ว',en:'Seller shipped'},THAILAND_RETURN_BATCH:{th:'ได้รอบส่งกลับไทย',en:'Thailand return batch assigned'},RETURNED_TO_THAI:{th:'ส่งกลับไทยแล้ว',en:'Returned to Thailand'},ARRIVING_SHOP_2_3_DAYS:{th:'รอของถึงร้าน 2–3 วัน',en:'Arriving at shop in 2–3 days'},BALANCE_DUE:{th:'รอชำระยอดคงเหลือ',en:'Balance payment due'},SHOP_PREPARING_SHIPMENT:{th:'ร้านเตรียมจัดส่ง',en:'Shop preparing shipment'},OUT_FOR_DELIVERY:{th:'กำลังจัดส่ง',en:'Out for delivery'},COMPLETED:{th:'จัดส่งสำเร็จ',en:'Completed'},EXPIRED:{th:'หมดเวลาชำระเงิน',en:'Payment window expired'},CANCELLED:{th:'ยกเลิกแล้ว',en:'Cancelled'}}
const orderStatusLabel=(locale:Locale,status:string)=>{const label=customerStatus[status];return label?text(locale,label.th,label.en):status}

export function OrdersPage({ locale, session, api, demo, pendingOrder, onPay }: { locale: Locale; session: SessionInfo | null; api: ApiClient | null; demo: boolean; pendingOrder: OrderSummary | null; onPay: (order: OrderSummary) => void }) {
  const [orders,setOrders]=useState<OrderSummary[]>(pendingOrder?[pendingOrder]:[]);const [loading,setLoading]=useState(Boolean(!demo&&api&&session));const [error,setError]=useState('')
  useEffect(()=>{if(!demo&&api&&session){setLoading(true);setError('');api.listOrders(session.token).then(setOrders).catch(cause=>setError(cause instanceof Error?cause.message:'โหลดออเดอร์ไม่สำเร็จ')).finally(()=>setLoading(false))}else setLoading(false)},[api,session?.token,demo])
  if(loading)return <div className="page orders-page"><section className="content-loading" aria-live="polite" aria-busy="true"><SpinnerGap className="spin" size={28}/><strong>{text(locale,'กำลังโหลดสถานะสินค้าและประวัติออเดอร์…','Loading item status and order history…')}</strong><span>{text(locale,'รอสักครู่ ระบบกำลังเตรียมข้อมูลล่าสุด','Please wait while the latest information is prepared')}</span><div className="skeleton-lines" aria-hidden="true"><i/><i/><i/></div></section></div>
  return <div className="page orders-page"><div className="section-heading"><div><h1>{text(locale,'สถานะสินค้าและคำสั่งซื้อ','Item status and orders')}</h1><p>{text(locale,'ทุกการเปลี่ยนสถานะจะแสดงเวลาที่บันทึกไว้ และส่งแจ้งเตือนทางอีเมล','Every status change includes its recorded time and is also emailed to you.')}</p></div></div>{error&&<p className="form-error" role="alert">{error}</p>}{orders.length===0?<div className="empty-state"><Package size={38}/><h2>{text(locale,'ยังไม่มีคำสั่งซื้อ','No orders yet')}</h2><p>{text(locale,'ออเดอร์ที่ยืนยันแล้วจะปรากฏที่นี่','Confirmed orders will appear here.')}</p></div>:<div className="customer-order-grid">{orders.map(order=><CustomerOrderCard key={order.id} locale={locale} order={order} onPay={onPay}/>)}</div>}</div>
}

function CustomerOrderCard({locale,order,onPay}:{locale:Locale;order:OrderSummary;onPay:(order:OrderSummary)=>void}){
  const history=order.history||[];const needsPayment=['AWAITING_PAYMENT','BALANCE_DUE'].includes(order.status)
  return <article className="customer-order-card" data-status={order.status}><header><div><span>{order.orderType==='PREORDER'?'Pre-order':text(locale,'พร้อมส่ง','Ready stock')}</span><h2>{order.reference}</h2><small>{new Date(order.createdAt).toLocaleString(locale==='th'?'th-TH':'en-GB')}</small></div><b className="status-badge" data-tone={order.status==='COMPLETED'?'success':order.status.includes('PAYMENT')||order.status==='BALANCE_DUE'?'warning':'purple'}>{orderStatusLabel(locale,order.status)}</b></header><dl><div><dt>{text(locale,'ยอดรวม','Total')}</dt><dd>฿{(order.subtotal+(order.shippingFee||0)).toLocaleString()}</dd></div><div><dt>{text(locale,'ชำระแล้ว','Paid')}</dt><dd>฿{order.totalPaid.toLocaleString()}</dd></div><div><dt>{text(locale,'คงเหลือ','Balance')}</dt><dd>฿{order.balanceDue.toLocaleString()}</dd></div></dl>{order.items&&<section className="customer-order-items"><strong>{text(locale,'สินค้าในออเดอร์','Items')}</strong>{order.items.map(item=><span key={item.id}>{item.titleSnapshot}<b>× {item.quantity}</b></span>)}</section>}<section className="customer-status-timeline"><div className="timeline-heading"><strong>{text(locale,'ลำดับสถานะสินค้า','Item status timeline')}</strong><span>{history.length} {text(locale,'เหตุการณ์','events')}</span></div>{history.length?history.map((row,index)=><div className="customer-timeline-step" key={row.id}><span className="timeline-marker">{index===history.length-1?<CheckCircle weight="fill"/>:<Circle weight="fill"/>}</span><div><strong>{orderStatusLabel(locale,row.toStatus)}</strong><time dateTime={row.createdAt}>{new Date(row.createdAt).toLocaleString(locale==='th'?'th-TH':'en-GB',{dateStyle:'medium',timeStyle:'short'})}</time>{row.note&&<p>{row.note}</p>}</div></div>):<p className="helper-text">{text(locale,'กำลังรอประวัติสถานะจากระบบ','Waiting for status history')}</p>}</section>{order.messages?.map(message=><p className="order-message" key={message.id}><strong>{text(locale,message.titleTh,message.titleEn)}</strong><br/>{text(locale,message.bodyTh,message.bodyEn)}</p>)}{needsPayment&&<section className="customer-payment-callout"><Timer size={24}/><div><strong>{text(locale,order.status==='BALANCE_DUE'?'ถึงรอบชำระยอดคงเหลือแล้ว':'กรุณาส่งหลักฐานการโอน',order.status==='BALANCE_DUE'?'Your balance payment is due':'Submit your payment proof')}</strong><span>{order.reservedUntil?text(locale,`ส่งสลิปภายใน ${new Date(order.reservedUntil).toLocaleString('th-TH')}`,`Submit by ${new Date(order.reservedUntil).toLocaleString('en-GB')}`):text(locale,'ระบบจะแสดงเวลาคงเหลือในหน้าชำระเงิน','The payment page will show the remaining time.')}</span></div><button className="primary-button" onClick={()=>onPay(order)}>{text(locale,order.status==='BALANCE_DUE'?'แนบสลิปยอดคงเหลือ':'แนบสลิปการโอน',order.status==='BALANCE_DUE'?'Upload balance slip':'Upload payment slip')}</button></section>}</article>
}

export function ProfilePage({ locale, session, api, theme, setTheme, signOut, requestAuth }: { locale: Locale; session: SessionInfo | null; api: ApiClient | null; theme: ThemePreference; setTheme: (v: ThemePreference) => void; signOut: () => void; requestAuth: () => void }) {
  const [notifications,setNotifications]=useState<UserNotification[]>([]);const [showNotifications,setShowNotifications]=useState(false);useEffect(()=>{if(api&&session)api.listNotifications(session.token).then(setNotifications).catch(()=>undefined)},[api,session?.token])
  return <div className="page narrow-page"><section className="profile-hero"><UserCircle size={48} weight="duotone" /><div><h1>{session?.user.displayName || text(locale, 'ผู้เยี่ยมชม', 'Guest')}</h1><p>{session?.user.email || text(locale, 'ลูกค้าและผู้ดูแลเข้าสู่ระบบด้วยอีเมลและรหัส OTP', 'Customers and admins sign in with email and an OTP.')}</p></div>{!session && <button className="primary-button" onClick={requestAuth}>{text(locale, 'เข้าสู่ระบบ', 'Sign in')}</button>}</section>
    {session && <><div className="role-badge">{session.user.role}</div><div className="points-panel"><Star size={28} weight="fill" /><div><span>{text(locale, 'แต้มสะสม', 'Reward points')}</span><strong>{session.user.pointsBalance.toLocaleString()}</strong></div></div></>}
    <div className="settings-list"><a href="#/orders"><Package /><span>{text(locale, 'คำสั่งซื้อของฉัน', 'My orders')}</span></a><a href="#/favorites"><Heart /><span>{text(locale, 'รายการโปรด', 'Favorites')}</span></a><button onClick={()=>setShowNotifications(!showNotifications)}><Bell /><span>{text(locale, `การแจ้งเตือน (${notifications.filter(n=>!n.readAt).length})`, `Notifications (${notifications.filter(n=>!n.readAt).length})`)}</span></button>{session && (session.user.role === 'ADMIN' || session.user.role === 'OWNER') && <a className="admin-entry" href="#/admin"><Gear /><span>{text(locale, 'เปิดหลังบ้าน', 'Open admin')}</span></a>}</div>{showNotifications&&<div className="notification-list">{notifications.length===0?<p>{text(locale,'ยังไม่มีการแจ้งเตือน','No notifications')}</p>:notifications.map(n=><button key={n.id} className={n.readAt?'':'is-unread'} onClick={async()=>{if(api&&session&&!n.readAt){await api.readNotification(session.token,n.id);setNotifications(notifications.map(x=>x.id===n.id?{...x,readAt:new Date().toISOString()}:x))}}}><strong>{text(locale,n.titleTh,n.titleEn)}</strong><span>{text(locale,n.bodyTh,n.bodyEn)}</span></button>)}</div>}
    <section className="appearance-panel"><h2>{text(locale, 'รูปแบบการแสดงผล', 'Appearance')}</h2><div className="theme-grid">{(['system', 'light', 'dark', 'contrast'] as ThemePreference[]).map((item) => <button key={item} className={theme === item ? 'is-active' : ''} onClick={() => setTheme(item)}>{item === 'system' ? text(locale, 'ตามอุปกรณ์', 'System') : item === 'light' ? text(locale, 'กลางวัน', 'Light') : item === 'dark' ? text(locale, 'กลางคืน', 'Dark') : text(locale, 'คอนทราสต์สูง', 'High contrast')}</button>)}</div></section>
    {session && <button className="danger-button" onClick={signOut}><SignOut />{text(locale, 'ออกจากระบบ', 'Sign out')}</button>}
  </div>
}
