import { useEffect, useState } from 'react'
import { ChartLineUp, Gear, Package, Receipt, WarningCircle, Wallet } from '@phosphor-icons/react'
import type { ApiClient } from '../api/client'
import type { Locale, SessionInfo } from '../domain/types'

const text = (locale: Locale, th: string, en: string) => locale === 'th' ? th : en
export function AdminPage({ locale, session, demo, api }: { locale: Locale; session: SessionInfo | null; demo: boolean; api: ApiClient | null }) {
  const [metrics, setMetrics] = useState<Record<string, number>>({ pendingPayments: 12, ordersToday: 38, lowStock: 7, failedJobs: 2 }); const [error, setError] = useState('')
  useEffect(() => { if (!demo && api && session) api.adminDashboard(session.token).then(setMetrics).catch((cause) => setError(cause instanceof Error ? cause.message : 'โหลด Dashboard ไม่สำเร็จ')) }, [demo, api, session])
  if (!demo && (!session || !['ADMIN', 'OWNER'].includes(session.user.role))) return <div className="page narrow-page"><div className="empty-state"><WarningCircle size={42} /><h1>{text(locale, 'ไม่มีสิทธิ์เปิดหลังบ้าน', 'Admin access required')}</h1><p>{text(locale, 'เข้าสู่ระบบด้วยบัญชี Admin หรือ Owner', 'Sign in with an Admin or Owner account.')}</p></div></div>
  return <div className="admin-page"><aside className="admin-sidebar"><strong>Admin</strong><a className="is-active" href="#/admin"><ChartLineUp />{text(locale, 'ภาพรวม', 'Overview')}</a><button><Receipt />{text(locale, 'ออเดอร์', 'Orders')}</button><button><Wallet />{text(locale, 'การชำระเงิน', 'Payments')}</button><button><Package />{text(locale, 'สินค้าและสต็อก', 'Products & stock')}</button><button><Gear />{text(locale, 'ตั้งค่าร้าน', 'Shop settings')}</button></aside>
    <section className="admin-workspace"><div className="section-heading"><div><h1>{text(locale, 'ภาพรวมร้านค้า', 'Shop overview')}</h1><p>{text(locale, 'รายการสำคัญที่ควรจัดการก่อน', 'Priority items that need attention.')}</p></div><button className="secondary-button">{text(locale, 'เพิ่มสินค้า', 'Add product')}</button></div>{error && <p className="form-error">{error}</p>}
      <div className="metric-grid"><Metric label={text(locale, 'รอตรวจสลิป', 'Pending slips')} value={metrics.pendingPayments || 0} /><Metric label={text(locale, 'ออเดอร์วันนี้', 'Orders today')} value={metrics.ordersToday || 0} /><Metric label={text(locale, 'สต็อกใกล้หมด', 'Low stock')} value={metrics.lowStock || 0} /><Metric label={text(locale, 'งานส่งไม่สำเร็จ', 'Failed jobs')} value={metrics.failedJobs || 0} /></div>
      <section className="admin-table-section"><div className="section-heading"><div><h2>{text(locale, 'ต้องจัดการก่อน', 'Needs attention')}</h2></div></div><div className="responsive-table"><table><thead><tr><th>{text(locale, 'รายการ', 'Item')}</th><th>{text(locale, 'ประเภท', 'Type')}</th><th>{text(locale, 'เวลา', 'Time')}</th><th>{text(locale, 'การทำงาน', 'Action')}</th></tr></thead><tbody><tr><td>#RD-0829-1042 · ฿477</td><td>{text(locale, 'สลิปใหม่', 'New slip')}</td><td>{text(locale, '2 นาทีที่แล้ว', '2 min ago')}</td><td><button>{text(locale, 'ตรวจสอบ', 'Review')}</button></td></tr><tr><td>{text(locale, 'รอบเกาหลีเดือนกันยายน', 'Korea September')}</td><td>Pre-order</td><td>{text(locale, 'เหลือ 3 ชั่วโมง', '3 hours left')}</td><td><button>{text(locale, 'เปิดรอบ', 'Open round')}</button></td></tr><tr><td>Email #JOB-192</td><td>{text(locale, 'ส่งไม่สำเร็จ', 'Failed')}</td><td>{text(locale, 'ลองแล้ว 3 ครั้ง', '3 attempts')}</td><td><button>{text(locale, 'ดูสาเหตุ', 'View error')}</button></td></tr></tbody></table></div></section>
    </section>
  </div>
}
function Metric({ label, value }: { label: string; value: number }) { return <article className="metric-card" data-animate-item><span>{label}</span><strong>{value.toLocaleString()}</strong></article> }
