import { useEffect, useState, type FormEvent } from 'react'
import { ChartLineUp, Gear, Megaphone, Package, Receipt, ShieldCheck, WarningCircle } from '@phosphor-icons/react'
import type { ApiClient } from '../api/client'
import type { AdminAccount, AdminDashboard, AdminWorkspace, Locale, Product, SessionInfo, ShopSettings, StorefrontData } from '../domain/types'
import { CatalogAdmin, ContentAdmin, OrdersAdmin, type ActivityController } from './AdminCrudPages'

type Tab = 'overview' | 'orders' | 'products' | 'content' | 'settings' | 'admins'
const text = (locale: Locale, th: string, en: string) => locale === 'th' ? th : en

export function AdminPage({ locale, session, demo, api, data, onDataChange }: { locale: Locale; session: SessionInfo | null; demo: boolean; api: ApiClient | null; data: StorefrontData; onDataChange: (data: StorefrontData) => void }) {
  const [tab, setTab] = useState<Tab>('overview')
  const [metrics, setMetrics] = useState<AdminDashboard>({ pendingPayments:0,ordersToday:0,lowStock:0,failedJobs:0,totalTransferred:0,totalOrders:0,totalItems:0,daily:[],productSales:[] })
  const [settings, setSettings] = useState<ShopSettings>(data.settings); const [admins, setAdmins] = useState<AdminAccount[]>([])
  const [workspace, setWorkspace] = useState<AdminWorkspace | null>(null)
  const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [busy, setBusy] = useState(false)
  const [activities,setActivities]=useState<Array<{id:string;label:string;state:'RUNNING'|'DONE'|'FAILED';error?:string}>>([])
  const activity:ActivityController={begin:(label)=>{const id=crypto.randomUUID();setActivities(current=>[...current,{id,label,state:'RUNNING'}]);return id},success:(id)=>setActivities(current=>current.map(item=>item.id===id?{...item,state:'DONE'}:item)),failure:(id,message)=>setActivities(current=>current.map(item=>item.id===id?{...item,state:'FAILED',error:message}:item))}
  useEffect(() => {
    if (demo || !api || !session) return
    Promise.all([api.adminDashboard(session.token), api.adminConfiguration(session.token), api.adminWorkspace(session.token)]).then(([dashboard, config, nextWorkspace]) => { setMetrics(dashboard); setSettings(config.settings); setAdmins(config.admins); setWorkspace(nextWorkspace) }).catch((cause) => setError(cause instanceof Error ? cause.message : 'โหลดหลังบ้านไม่สำเร็จ'))
  }, [demo, api, session?.token])
  if (!demo && (!session || !['ADMIN', 'OWNER'].includes(session.user.role))) return <div className="page narrow-page"><div className="empty-state"><WarningCircle size={42} /><h1>{text(locale, 'ไม่มีสิทธิ์เปิดหลังบ้าน', 'Admin access required')}</h1><p>{text(locale, 'ระบบตรวจสิทธิ์ล่าสุดจากฐานข้อมูลแล้ว กรุณาเข้าสู่ระบบด้วยบัญชี Admin หรือ Owner', 'Sign in with an Admin or Owner account. Permissions are checked against the database.')}</p></div></div>
  const chooseTab = (next: Tab) => { setTab(next); setError(''); setNotice('') }
  const tabs: { id: Tab; label: string; icon: React.ReactNode }[] = [
    { id: 'overview', label: text(locale, 'ภาพรวม', 'Overview'), icon: <ChartLineUp /> },
    { id: 'orders', label: text(locale, 'ออเดอร์และสลิป', 'Orders & slips'), icon: <Receipt /> },
    { id: 'products', label: text(locale, 'สินค้าและค่าจัดส่ง', 'Products & shipping'), icon: <Package /> },
    { id: 'content', label: text(locale, 'เนื้อหาและ Pre-order', 'Content & pre-order'), icon: <Megaphone /> },
    { id: 'settings', label: text(locale, 'ตั้งค่าร้านและหน้าโหลด', 'Store & loader'), icon: <Gear /> },
    { id: 'admins', label: text(locale, 'ผู้ดูแลระบบ', 'Administrators'), icon: <ShieldCheck /> },
  ]
  return <div className="admin-page">
    <aside className="admin-sidebar"><strong>Admin · {session?.user.role || 'DEMO'}</strong>{tabs.map((item) => <button key={item.id} className={tab === item.id ? 'is-active' : ''} onClick={() => chooseTab(item.id)}>{item.icon}{item.label}</button>)}</aside>
    <section className="admin-workspace">
      <div className="admin-mobile-tabs">{tabs.map((item) => <button key={item.id} className={tab === item.id ? 'is-active' : ''} onClick={() => chooseTab(item.id)}>{item.icon}<span>{item.label}</span></button>)}</div>
      {error && <p className="form-error" role="alert">{error}</p>}{notice && <p className="form-success" role="status">{notice}</p>}
      {tab === 'overview' && <Overview locale={locale} metrics={metrics} />}
      {tab === 'orders' && workspace && api && session && <OrdersAdmin locale={locale} workspace={workspace} busy={busy} api={api} token={session.token} refresh={async () => setWorkspace(await api.adminWorkspace(session.token))} report={setNotice} fail={setError} setBusy={setBusy} activity={activity} />}
      {tab === 'products' && workspace && api && session && <CatalogAdmin locale={locale} workspace={workspace} busy={busy} api={api} token={session.token} refresh={async () => { const next = await api.adminWorkspace(session.token); setWorkspace(next); onDataChange({ ...data, products: next.products, categories: next.categories }) }} report={setNotice} fail={setError} setBusy={setBusy} activity={activity} />}
      {tab === 'content' && workspace && api && session && <ContentAdmin locale={locale} workspace={workspace} busy={busy} api={api} token={session.token} refresh={async () => setWorkspace(await api.adminWorkspace(session.token))} report={setNotice} fail={setError} setBusy={setBusy} activity={activity} />}
      {tab === 'settings' && <SettingsForm locale={locale} settings={settings} busy={busy} onChange={setSettings} onSave={async () => { setBusy(true); setError(''); try { const saved = !demo && api && session ? await api.adminSaveSettings(session.token, settings) : settings; setSettings(saved); onDataChange({ ...data, settings: saved }); localStorage.setItem('shop.loader-settings', JSON.stringify(saved)); setNotice(text(locale, 'บันทึกการตั้งค่าร้านแล้ว', 'Shop settings saved')) } catch (cause) { setError(cause instanceof Error ? cause.message : 'บันทึกไม่สำเร็จ') } finally { setBusy(false) } }} />}
      {tab === 'admins' && <AdminsPanel locale={locale} role={session?.user.role || 'OWNER'} admins={admins} busy={busy} onAdd={async (email, displayName) => { setBusy(true); setError(''); try { const added = !demo && api && session ? await api.adminAddAdmin(session.token, email, displayName) : { id: crypto.randomUUID(), email, displayName, role: 'ADMIN' as const, status: 'ACTIVE' }; setAdmins((current) => [...current.filter((item) => item.email !== added.email), added]); setNotice(text(locale, 'เพิ่มผู้ดูแลแล้ว บัญชีนี้ล็อกอินด้วย OTP ได้ทันที', 'Administrator added and can now sign in with an OTP')) } catch (cause) { setError(cause instanceof Error ? cause.message : 'เพิ่มผู้ดูแลไม่สำเร็จ') } finally { setBusy(false) } }} />}
    </section><ActivityCapsule locale={locale} activities={activities}/>
  </div>
}

function ActivityCapsule({locale,activities}:{locale:Locale;activities:Array<{id:string;label:string;state:'RUNNING'|'DONE'|'FAILED';error?:string}>}){if(!activities.length)return null;const running=activities.filter(x=>x.state==='RUNNING').length;const failed=activities.filter(x=>x.state==='FAILED').length;const done=activities.filter(x=>x.state==='DONE').length;const current=activities.slice().reverse().find(x=>x.state==='RUNNING')||activities[activities.length-1];return <aside className={`activity-capsule ${failed?'has-error':running?'is-running':'is-done'}`} role="status" aria-live="polite"><span className="activity-pulse"/><div><strong>{running?text(locale,`กำลังบันทึก ${running} จาก ${activities.length} รายการ`,`Saving ${running} of ${activities.length}`):failed?text(locale,`สำเร็จ ${done} · ไม่สำเร็จ ${failed}`,`${done} done · ${failed} failed`):text(locale,`บันทึกสำเร็จ ${done} รายการ`,`${done} changes saved`)}</strong><small>{current.error||current.label}</small></div><progress max={activities.length} value={done+failed}/></aside>}

function Overview({ locale, metrics }: { locale: Locale; metrics: AdminDashboard }) {
  return <><div className="section-heading"><div><h1>{text(locale, 'ภาพรวมร้านค้า', 'Shop overview')}</h1><p>{text(locale, 'ยอดโอนที่ยืนยันแล้วและแนวโน้ม 14 วันล่าสุด', 'Confirmed transfers and the latest 14-day trend.')}</p></div></div><div className="metric-grid"><Metric money label={text(locale, 'ยอดเงินเข้ายืนยันแล้ว', 'Confirmed transfers')} value={metrics.totalTransferred || 0} /><Metric label={text(locale, 'รอตรวจสลิป', 'Pending slips')} value={metrics.pendingPayments || 0} /><Metric label={text(locale, 'ออเดอร์ทั้งหมด', 'Total orders')} value={metrics.totalOrders || 0} /><Metric label={text(locale, 'จำนวนชิ้นที่สั่ง', 'Items ordered')} value={metrics.totalItems || 0} /><Metric label={text(locale, 'ออเดอร์วันนี้', 'Orders today')} value={metrics.ordersToday || 0} /><Metric label={text(locale, 'สต็อกใกล้หมด', 'Low stock')} value={metrics.lowStock || 0} /><Metric label={text(locale, 'งานส่งไม่สำเร็จ', 'Failed jobs')} value={metrics.failedJobs || 0} /></div><div className="dashboard-charts"><TrendChart locale={locale} data={metrics.daily}/><ProductSalesChart locale={locale} data={metrics.productSales}/></div></>
}

function TrendChart({locale,data}:{locale:Locale;data:AdminDashboard['daily']}){const width=720,height=240,pad=34;const max=Math.max(1,...data.flatMap(x=>[x.revenue,x.orders*100,x.items*60]));const points=(key:'revenue'|'orders'|'items',factor=1)=>data.map((row,index)=>`${pad+(index*Math.max(1,width-pad*2))/Math.max(1,data.length-1)},${height-pad-(row[key]*factor*(height-pad*2))/max}`).join(' ');return <section className="chart-card"><div><h2>{text(locale,'แนวโน้ม 14 วัน','14-day trend')}</h2><span className="chart-legend"><i data-series="revenue"/>{text(locale,'ยอดเงิน','Revenue')} <i data-series="orders"/>{text(locale,'ออเดอร์','Orders')} <i data-series="items"/>{text(locale,'ชิ้น','Items')}</span></div>{data.length?<svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={text(locale,'กราฟยอดเงิน ออเดอร์ และจำนวนชิ้นย้อนหลัง','Revenue, orders, and items trend')}><polyline data-series="revenue" points={points('revenue')}/><polyline data-series="orders" points={points('orders',100)}/><polyline data-series="items" points={points('items',60)}/>{data.map((row,index)=><text key={row.date} x={pad+(index*(width-pad*2))/Math.max(1,data.length-1)} y={height-8}>{index%3===0?row.date.slice(5):''}</text>)}</svg>:<p>{text(locale,'ยังไม่มีข้อมูล','No data yet')}</p>}</section>}
function ProductSalesChart({locale,data}:{locale:Locale;data:AdminDashboard['productSales']}){const max=Math.max(1,...data.map(x=>x.revenue));return <section className="chart-card product-sales-chart"><div><h2>{text(locale,'ยอดขายรายสินค้า','Sales by product')}</h2><span>{text(locale,'เรียงตามมูลค่าออเดอร์','Ranked by order value')}</span></div>{data.length?data.map(item=><div className="sales-row" key={item.productId}><span>{text(locale,item.nameTh,item.nameEn)}</span><div><i style={{transform:`scaleX(${item.revenue/max})`}}/></div><strong>฿{item.revenue.toLocaleString()} · {item.quantity}</strong></div>):<p>{text(locale,'ยังไม่มีข้อมูล','No data yet')}</p>}</section>}

function SettingsForm({ locale, settings, busy, onChange, onSave }: { locale: Locale; settings: ShopSettings; busy: boolean; onChange: (settings: ShopSettings) => void; onSave: () => void }) {
  const field = <K extends keyof ShopSettings>(key: K, value: ShopSettings[K]) => onChange({ ...settings, [key]: value })
  return <form className="admin-form" onSubmit={(event) => { event.preventDefault(); onSave() }}><div className="section-heading"><div><h1>{text(locale, 'ตั้งค่าร้านและหน้าโหลด', 'Store and loading screen')}</h1><p>{text(locale, 'ข้อความทุกส่วนและโลโก้หน้าแรกเปลี่ยนได้จากที่นี่', 'Customize every loading-screen message and logo here.')}</p></div></div>
    <div className="form-grid"><Field label="ชื่อร้าน (ไทย)"><input value={settings.storeNameTh} onChange={(event) => field('storeNameTh', event.target.value)} /></Field><Field label="Store name (English)"><input value={settings.storeNameEn} onChange={(event) => field('storeNameEn', event.target.value)} /></Field><Field label={text(locale, 'URL โลโก้ร้าน', 'Shop logo URL')}><input type="url" value={settings.logoUrl || ''} onChange={(event) => field('logoUrl', event.target.value)} /></Field><Field label={text(locale, 'สีหลัก', 'Primary color')}><input type="color" value={settings.primaryColor} onChange={(event) => field('primaryColor', event.target.value)} /></Field></div>
    <h2>{text(locale, 'หน้าโหลดแรก', 'Opening loader')}</h2><div className="form-grid"><Field label="ข้อความบน (ไทย)"><input value={settings.loaderKickerTh} onChange={(event) => field('loaderKickerTh', event.target.value)} /></Field><Field label="Kicker (English)"><input value={settings.loaderKickerEn} onChange={(event) => field('loaderKickerEn', event.target.value)} /></Field><Field label="หัวเรื่อง (ไทย)"><input value={settings.loaderTitleTh} placeholder={settings.storeNameTh} onChange={(event) => field('loaderTitleTh', event.target.value)} /></Field><Field label="Title (English)"><input value={settings.loaderTitleEn} placeholder={settings.storeNameEn} onChange={(event) => field('loaderTitleEn', event.target.value)} /></Field><Field label="ข้อความกำลังโหลด (ไทย)"><input value={settings.loaderMessageTh} onChange={(event) => field('loaderMessageTh', event.target.value)} /></Field><Field label="Loading message (English)"><input value={settings.loaderMessageEn} onChange={(event) => field('loaderMessageEn', event.target.value)} /></Field><Field label={text(locale, 'URL โลโก้หน้าโหลด', 'Loader logo URL')}><input type="url" value={settings.loaderLogoUrl || ''} onChange={(event) => field('loaderLogoUrl', event.target.value)} /></Field></div>
    <h2>{text(locale, 'รูปแบบค่าจัดส่ง', 'Shipping model')}</h2><div className="shipping-choice"><label><input type="radio" name="shippingMode" checked={settings.shippingMode === 'CART'} onChange={() => field('shippingMode', 'CART')} /><span><strong>{text(locale, 'รวมทั้งตะกร้า', 'One fee per cart')}</strong><small>{text(locale, 'คิดค่าจัดส่งครั้งเดียวต่อออเดอร์', 'Charge shipping once per order')}</small></span></label><label><input type="radio" name="shippingMode" checked={settings.shippingMode === 'ITEM'} onChange={() => field('shippingMode', 'ITEM')} /><span><strong>{text(locale, 'แยกตามสินค้า', 'Per item')}</strong><small>{text(locale, 'รวมค่าจัดส่งต่อชิ้นของแต่ละรายการ', 'Sum each product’s per-unit shipping')}</small></span></label></div>{settings.shippingMode === 'CART' && <Field label={text(locale, 'ค่าจัดส่งรวมต่อออเดอร์', 'Shipping per order')}><input type="number" min="0" inputMode="decimal" value={settings.cartShippingFee} onChange={(event) => field('cartShippingFee', Number(event.target.value))} /></Field>}
    {settings.pointsEnabled&&<div className="form-grid"><Field label={text(locale,'จำนวนแต้มต่อส่วนลด 1 บาท','Points per ฿1 discount')}><input type="number" min="1" value={settings.pointsPerBaht} onChange={e=>field('pointsPerBaht',Number(e.target.value))}/></Field><Field label={text(locale,'แต้มขั้นต่ำที่ใช้','Minimum redeem points')}><input type="number" min="0" value={settings.minimumRedeemPoints} onChange={e=>field('minimumRedeemPoints',Number(e.target.value))}/></Field><Field label={text(locale,'ส่วนลดสูงสุด %','Maximum discount %')}><input type="number" min="0" max="100" value={settings.maxRedeemPercent} onChange={e=>field('maxRedeemPercent',Number(e.target.value))}/></Field></div>}<div className="feature-switches"><Toggle label={text(locale, 'ระบบรายการโปรด', 'Favorites')} checked={settings.favoritesEnabled} onChange={(value) => field('favoritesEnabled', value)} /><Toggle label={text(locale, 'ระบบแต้มสะสม', 'Reward points')} checked={settings.pointsEnabled} onChange={(value) => field('pointsEnabled', value)} /><Toggle label={text(locale, 'ระบบรีวิว', 'Reviews')} checked={settings.reviewsEnabled} onChange={(value) => field('reviewsEnabled', value)} /></div><button className="primary-button" disabled={busy}>{busy ? text(locale, 'กำลังบันทึก…', 'Saving…') : text(locale, 'บันทึกการตั้งค่าทั้งหมด', 'Save all settings')}</button>
  </form>
}

function ProductsSettings({ locale, products, shippingMode, busy, onSave }: { locale: Locale; products: Product[]; shippingMode: 'CART' | 'ITEM'; busy: boolean; onSave: (product: Product) => void }) {
  const [fees, setFees] = useState<Record<string, number>>(() => Object.fromEntries(products.map((product) => [product.id, product.shippingFee || 0])))
  return <div><div className="section-heading"><div><h1>{text(locale, 'สินค้าและค่าจัดส่ง', 'Products and shipping')}</h1><p>{shippingMode === 'ITEM' ? text(locale, 'ระบบจะคิดค่าจัดส่งต่อชิ้น × จำนวน', 'Shipping is calculated per unit × quantity.') : text(locale, 'ขณะนี้ใช้ค่าจัดส่งรวมทั้งตะกร้า ค่าแยกจะถูกเก็บไว้สำหรับสลับภายหลัง', 'Cart-wide shipping is active; item fees are saved for later use.')}</p></div></div><div className="admin-product-list">{products.map((product) => <article key={product.id}><div className="admin-product-thumb">{product.imageUrls[0] ? <img src={product.imageUrls[0]} alt="" /> : <span>1:1</span>}</div><div><strong>{text(locale, product.titleTh, product.titleEn)}</strong><small>{product.type} · ฿{product.price.toLocaleString()}</small></div><label><span>{text(locale, 'ค่าส่ง/ชิ้น', 'Shipping/unit')}</span><input type="number" min="0" inputMode="decimal" value={fees[product.id] ?? 0} onChange={(event) => setFees({ ...fees, [product.id]: Number(event.target.value) })} /></label><button className="secondary-button" disabled={busy} onClick={() => onSave({ ...product, shippingFee: fees[product.id] || 0 })}>{text(locale, 'บันทึก', 'Save')}</button></article>)}</div></div>
}

function AdminsPanel({ locale, role, admins, busy, onAdd }: { locale: Locale; role: string; admins: AdminAccount[]; busy: boolean; onAdd: (email: string, displayName: string) => void }) {
  const [email, setEmail] = useState(''); const [displayName, setDisplayName] = useState('')
  const submit = (event: FormEvent) => { event.preventDefault(); if (!email) return; onAdd(email, displayName); setEmail(''); setDisplayName('') }
  return <div><div className="section-heading"><div><h1>{text(locale, 'ผู้ดูแลระบบ', 'Administrators')}</h1><p>{text(locale, 'Owner เพิ่มอีเมลล่วงหน้าได้ ผู้ดูแลคนนั้นจะเข้าใช้งานด้วย OTP', 'The Owner can pre-authorize an email; that administrator signs in with an OTP.')}</p></div></div>{role === 'OWNER' ? <form className="admin-add-form" onSubmit={submit}><Field label={text(locale, 'อีเมลผู้ดูแล', 'Administrator email')}><input type="email" required value={email} onChange={(event) => setEmail(event.target.value)} /></Field><Field label={text(locale, 'ชื่อที่แสดง (ไม่บังคับ)', 'Display name (optional)')}><input value={displayName} onChange={(event) => setDisplayName(event.target.value)} /></Field><button className="primary-button" disabled={busy}>{text(locale, 'เพิ่มผู้ดูแล', 'Add administrator')}</button></form> : <p className="inline-alert warning">{text(locale, 'เฉพาะ Owner เท่านั้นที่เพิ่มผู้ดูแลได้', 'Only the Owner can add administrators.')}</p>}<div className="admin-list">{admins.map((admin) => <article key={admin.id}><ShieldCheck size={24} /><div><strong>{admin.displayName || admin.email}</strong><span>{admin.email}</span></div><b>{admin.role}</b></article>)}</div></div>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="admin-field"><span>{label}</span>{children}</label> }
function Toggle({ label, checked, onChange }: { label: string; checked: boolean; onChange: (checked: boolean) => void }) { return <label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /></label> }
function Metric({ label, value,money=false }: { label: string; value: number;money?:boolean }) { return <article className="metric-card" data-animate-item><span>{label}</span><strong>{money?'฿':''}{value.toLocaleString()}</strong></article> }
