import { useMemo, useState, type FormEvent } from 'react'
import { CheckCircle,Eye,Funnel,SpinnerGap,XCircle } from '@phosphor-icons/react'
import type { ApiClient } from '../api/client'
import type { AdminWorkspace, Announcement, Category, Locale, PaymentAccount, PreorderCampaign, Product } from '../domain/types'
import { MediaImage } from '../components/MediaImage'
import { RichContentEditor } from '../components/RichContent'
import { prepareImage } from '../lib/images'

const tx=(l:Locale,th:string,en:string)=>l==='th'?th:en
export type ActivityController={begin:(label:string)=>string;success:(id:string)=>void;failure:(id:string,message:string)=>void}
type Shared={locale:Locale;workspace:AdminWorkspace;busy:boolean;api:ApiClient;token:string;refresh:()=>Promise<void>;report:(v:string)=>void;fail:(v:string)=>void;setBusy:(v:boolean)=>void;activity:ActivityController}
const run=async(p:Shared,work:()=>Promise<unknown>,message:string)=>{const id=p.activity.begin(message);p.fail('');try{await work();p.activity.success(id);p.report(message);void p.refresh().catch(()=>undefined);return true}catch(e){const detail=e instanceof Error?e.message:'บันทึกไม่สำเร็จ';p.activity.failure(id,detail);p.fail(detail);return false}}
const Field=({label,children}:{label:string;children:React.ReactNode})=><label className="admin-field"><span>{label}</span>{children}</label>

export function OrdersAdmin(p:Shared){
  const [notes,setNotes]=useState<Record<string,string>>({});const [visible,setVisible]=useState<string[]>(()=>[...new Set([...p.workspace.statuses.map(s=>s.id),...p.workspace.orders.map(o=>o.status)])]);const [working,setWorking]=useState('');const [feedback,setFeedback]=useState<Record<string,string>>({});const [slip,setSlip]=useState<{src:string;name:string}|null>(null)
  const filterStatuses=useMemo(()=>{const rows=[...p.workspace.statuses];p.workspace.orders.forEach(order=>{if(!rows.some(row=>row.id===order.status))rows.push({id:order.status,th:order.status,en:order.status})});return rows},[p.workspace.statuses,p.workspace.orders])
  const orders=useMemo(()=>p.workspace.orders.filter(order=>visible.includes(order.status)),[p.workspace.orders,visible])
  const act=async(key:string,work:()=>Promise<unknown>,message:string)=>{if(working)return;setWorking(key);setFeedback({...feedback,[key]:tx(p.locale,'กำลังบันทึก…','Saving…')});const saved=await run(p,work,message);setFeedback(current=>({...current,[key]:saved?message:tx(p.locale,'บันทึกไม่สำเร็จ โปรดลองอีกครั้ง','Could not save. Please retry.')}));setWorking('');navigator.vibrate?.(18)}
  const openSlip=async(id:string)=>{const key=`slip:${id}`;setWorking(key);try{const file=await p.api.adminFile(p.token,id);setSlip({name:file.fileName,src:`data:${file.mimeType};base64,${file.base64}`})}catch(e){p.fail(e instanceof Error?e.message:'เปิดสลิปไม่สำเร็จ')}finally{setWorking('')}}
  return <div><Header title={tx(p.locale,'ออเดอร์และการชำระเงิน','Orders and payments')} sub={tx(p.locale,'ตรวจสลิป เปลี่ยนสถานะ และส่งข้อความพิเศษถึงลูกค้า','Review slips, update status and send customer messages.')} />
    <section className="order-filters"><div><Funnel/><strong>{tx(p.locale,'แสดงสถานะ','Visible statuses')}</strong><span>{orders.length}/{p.workspace.orders.length}</span></div><div>{filterStatuses.map(status=><label key={status.id} data-tone={statusTone(status.id)}><input type="checkbox" checked={visible.includes(status.id)} onChange={e=>setVisible(e.target.checked?[...visible,status.id]:visible.filter(id=>id!==status.id))}/><span>{tx(p.locale,status.th,status.en)}</span></label>)}</div></section>
    <div className="admin-order-list">{orders.length===0?<div className="empty-state"><Funnel size={32}/><h2>{tx(p.locale,'ไม่มีออเดอร์ในสถานะที่เลือก','No orders match these filters')}</h2></div>:orders.map(o=><article key={o.id} data-status-tone={statusTone(o.status)}><div className="order-admin-head"><div><strong>{o.reference}</strong><span>{o.userEmail} · ฿{(o.subtotal+o.shippingFee).toLocaleString()}</span></div><b className="status-badge" data-tone={statusTone(o.status)}>{statusLabel(p,o.status)}</b></div>{o.shipping&&<address>{o.shipping.name} · {o.shipping.phone}<br/>{o.shipping.address}</address>}{o.payment&&<div className="payment-review"><span>฿{Number(o.payment.amount).toLocaleString()} · {o.payment.status}</span>{o.payment.slipFileId&&<button className="slip-button" onClick={()=>openSlip(o.payment!.slipFileId!)} disabled={working===`slip:${o.payment.slipFileId}`}>{working===`slip:${o.payment.slipFileId}`?<SpinnerGap className="spin"/>:<Eye/>}{tx(p.locale,'ดูสลิปในแอป','View slip')}</button>}{o.payment.status==='PENDING_REVIEW'&&<div><button className="approve-button" disabled={Boolean(working)} onClick={()=>act(`approve:${o.id}`,()=>p.api.adminReviewPayment(p.token,o.payment!.id,true,notes[o.id]),tx(p.locale,'ยืนยันสลิปแล้ว','Payment approved'))}>{working===`approve:${o.id}`?<SpinnerGap className="spin"/>:<CheckCircle/>}{tx(p.locale,'ยืนยัน','Approve')}</button><button className="reject-button" disabled={Boolean(working)} onClick={()=>act(`reject:${o.id}`,()=>p.api.adminReviewPayment(p.token,o.payment!.id,false,notes[o.id]),tx(p.locale,'ปฏิเสธสลิปแล้ว','Payment rejected'))}>{working===`reject:${o.id}`?<SpinnerGap className="spin"/>:<XCircle/>}{tx(p.locale,'ปฏิเสธ','Reject')}</button></div>}</div>}<div className="order-admin-actions"><select value={o.status} data-tone={statusTone(o.status)} onChange={e=>act(`status:${o.id}`,()=>p.api.adminTransitionOrder(p.token,o.id,e.target.value,notes[o.id]),tx(p.locale,'เปลี่ยนสถานะแล้ว','Status updated'))}>{p.workspace.statuses.map(s=><option key={s.id} value={s.id}>{tx(p.locale,s.th,s.en)}</option>)}</select><textarea placeholder={tx(p.locale,'หมายเหตุหรือข้อความพิเศษ','Note or customer message')} value={notes[o.id]||''} onChange={e=>setNotes({...notes,[o.id]:e.target.value})}/><button className="secondary-button" onClick={()=>act(`message:${o.id}`,()=>p.api.adminSendMessage(p.token,o.id,notes[o.id]||'',notes[o.id]||'',true),tx(p.locale,'ส่งข้อความและอีเมลเข้าคิวแล้ว','Message queued'))}>{tx(p.locale,'ส่งข้อความถึงลูกค้า','Message customer')}</button></div>{Object.entries(feedback).filter(([key])=>key.endsWith(o.id)).slice(-1).map(([key,value])=><p className="action-feedback" key={key}><CheckCircle/>{value}</p>)}</article>)}</div>
    {slip&&<div className="slip-modal" role="dialog" aria-modal="true" aria-label={tx(p.locale,'หลักฐานการโอน','Payment slip')} onClick={()=>setSlip(null)}><div onClick={e=>e.stopPropagation()}><header><strong>{slip.name}</strong><button onClick={()=>setSlip(null)}>×</button></header><img src={slip.src} alt={tx(p.locale,'หลักฐานการโอน','Payment slip')}/></div></div>}
  </div>
}
const statusTone=(status:string)=>status.includes('REJECT')||status.includes('EXPIRED')?'danger':status==='COMPLETED'?'success':status.includes('REVIEW')||status.includes('AWAIT')?'warning':status.includes('CONFIRMED')?'info':status.includes('SHIP')||status.includes('DELIVERY')?'purple':'neutral'
const statusLabel=(p:Shared,id:string)=>{const row=p.workspace.statuses.find(s=>s.id===id);return row?tx(p.locale,row.th,row.en):id}

const blankProduct:Product={id:'',type:'READY',titleTh:'',titleEn:'',descriptionTh:'',descriptionEn:'',price:0,shippingFee:0,deposit:0,stockOnHand:0,reservedQuantity:0,purchaseLimit:1,points:0,active:true,reviewEnabled:true,imageUrls:[],categoryId:'ready',contentEnabled:false,content:[]}
export function CatalogAdmin(p:Shared){
  const [edit,setEdit]=useState<Product>(blankProduct)
  const save=(e:FormEvent)=>{e.preventDefault();void run(p,()=>p.api.adminSaveProduct(p.token,{...edit,id:edit.id||crypto.randomUUID()}),tx(p.locale,'บันทึกสินค้าแล้ว','Product saved')).then(saved=>{if(saved)setEdit(blankProduct)})}
  const activityWork=async(label:string,work:()=>Promise<unknown>)=>{const id=p.activity.begin(label);try{const result=await work();p.activity.success(id);return result}catch(e){p.activity.failure(id,e instanceof Error?e.message:'Upload failed');throw e}}
  return <div><Header title={tx(p.locale,'สินค้าและหมวดหมู่','Products and categories')} sub={tx(p.locale,'จัดการรูปหลายรูป เนื้อหาแบบบทความ สต็อก แต้ม และค่าจัดส่ง','Manage multiple images, rich content, stock, points, and shipping.')} />
    <form className="admin-form admin-editor" onSubmit={save}><div className="form-grid"><Field label="ชื่อสินค้า (ไทย)"><input required value={edit.titleTh} onChange={e=>setEdit({...edit,titleTh:e.target.value})}/></Field><Field label="Product name (English)"><input value={edit.titleEn} onChange={e=>setEdit({...edit,titleEn:e.target.value})}/></Field><Field label={tx(p.locale,'ประเภท','Type')}><select value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value as Product['type']})}><option value="READY">READY</option><option value="PREORDER">PREORDER</option></select></Field><Field label={tx(p.locale,'หมวดหมู่','Category')}><select value={edit.categoryId} onChange={e=>setEdit({...edit,categoryId:e.target.value})}>{p.workspace.categories.map(c=><option key={c.id} value={c.id}>{tx(p.locale,c.nameTh,c.nameEn)}</option>)}</select></Field><Num label={tx(p.locale,'ราคา','Price')} value={edit.price} set={v=>setEdit({...edit,price:v})}/><Num label={tx(p.locale,'มัดจำ','Deposit')} value={edit.deposit} set={v=>setEdit({...edit,deposit:v})}/><Num label={tx(p.locale,'สต็อก/โควตา','Stock/capacity')} value={edit.stockOnHand} set={v=>setEdit({...edit,stockOnHand:v})}/><Num label={tx(p.locale,'จำกัดต่อคน','Limit/customer')} value={edit.purchaseLimit} set={v=>setEdit({...edit,purchaseLimit:v})}/><Num label={tx(p.locale,'แต้มที่จะได้รับ','Points earned')} value={edit.points} set={v=>setEdit({...edit,points:v})}/><Num label={tx(p.locale,'ค่าจัดส่งต่อชิ้น','Shipping/unit')} value={edit.shippingFee} set={v=>setEdit({...edit,shippingFee:v})}/></div>
      <Field label={tx(p.locale,'รายละเอียดสั้นภาษาไทย','Short Thai description')}><textarea value={edit.descriptionTh} onChange={e=>setEdit({...edit,descriptionTh:e.target.value})}/></Field><Field label={tx(p.locale,'รายละเอียดสั้นภาษาอังกฤษ','Short English description')}><textarea value={edit.descriptionEn} onChange={e=>setEdit({...edit,descriptionEn:e.target.value})}/></Field>
      <ImageUploader p={p} kind="PRODUCT_IMAGE" values={edit.imageUrls} onChange={imageUrls=>setEdit({...edit,imageUrls})}/>
      {edit.type==='PREORDER'&&<Field label="Pre-order campaign"><select value={edit.preorderCampaignId||''} onChange={e=>setEdit({...edit,preorderCampaignId:e.target.value})}><option value="">—</option>{p.workspace.campaigns.map(c=><option key={c.id} value={c.id}>{tx(p.locale,c.nameTh,c.nameEn)}</option>)}</select></Field>}
      <div className="feature-switches"><Check label={tx(p.locale,'เปิดขาย','Active')} checked={edit.active} set={v=>setEdit({...edit,active:v})}/><Check label={tx(p.locale,'เปิดรีวิว','Reviews')} checked={edit.reviewEnabled} set={v=>setEdit({...edit,reviewEnabled:v})}/><Check label={tx(p.locale,'เขียนรายละเอียดเพิ่มเติมแบบ Blog','Enable rich product story')} checked={Boolean(edit.contentEnabled)} set={v=>setEdit({...edit,contentEnabled:v})}/></div>
      {edit.contentEnabled&&<RichContentEditor blocks={edit.content||[]} onChange={content=>setEdit({...edit,content})} locale={p.locale} api={p.api} token={p.token} onActivity={activityWork}/>}<button className="primary-button">{tx(p.locale,edit.id?'บันทึกการแก้ไข':'เพิ่มสินค้า',edit.id?'Save changes':'Add product')}</button>
    </form>
    <div className="admin-product-list">{p.workspace.products.map(x=><article key={x.id}><div className="admin-product-thumb"><MediaImage src={x.imageUrls[0]} alt=""/></div><div><strong>{tx(p.locale,x.titleTh,x.titleEn)}</strong><small>{x.type} · ฿{x.price.toLocaleString()} · {tx(p.locale,'คงเหลือ','stock')} {x.stockOnHand}</small></div><button className="secondary-button" onClick={()=>setEdit(x)}>{tx(p.locale,'แก้ไข','Edit')}</button><button className="secondary-button" onClick={()=>run(p,()=>p.api.adminSetEntityActive(p.token,'product',x.id,!x.active),tx(p.locale,'เปลี่ยนการแสดงผลแล้ว','Visibility updated'))}>{x.active?tx(p.locale,'ปิดขาย','Disable'):tx(p.locale,'เปิดขาย','Enable')}</button></article>)}</div><CategoryEditor {...p}/>
  </div>
}

function ImageUploader({p,kind,values,onChange}:{p:Shared;kind:'PRODUCT_IMAGE'|'ANNOUNCEMENT_IMAGE';values:string[];onChange:(v:string[])=>void}){const [uploading,setUploading]=useState(false);const upload=async(files:FileList|null)=>{if(!files?.length)return;setUploading(true);for(const file of Array.from(files)){const id=p.activity.begin(tx(p.locale,`กำลังอัปโหลด ${file.name}`,`Uploading ${file.name}`));try{const prepared=await prepareImage(file);const saved=await p.api.adminUploadMedia(p.token,{kind,fileName:prepared.fileName,mimeType:prepared.mimeType,base64:prepared.base64});onChange([...values,saved.ref]);values=[...values,saved.ref];p.activity.success(id)}catch(e){p.activity.failure(id,e instanceof Error?e.message:'Upload failed')}}setUploading(false)};return <section className="image-uploader"><div><strong>{tx(p.locale,'รูปภาพ','Images')}</strong><small>{tx(p.locale,'เลือกได้หลายรูป ระบบจะย่อและบีบอัดก่อนอัปโหลด','Select multiple images; they are resized and compressed before upload.')}</small></div><label className={uploading?'is-busy':''}>{uploading?<SpinnerGap className="spin"/>:<Eye/>}{tx(p.locale,uploading?'กำลังอัปโหลด…':'เลือกรูปจากเครื่อง',uploading?'Uploading…':'Choose images')}<input type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>upload(e.target.files)}/></label><div className="uploaded-images">{values.map((value,index)=><figure key={`${value}-${index}`}><MediaImage src={value} alt=""/><button type="button" onClick={()=>onChange(values.filter((_,i)=>i!==index))}>×</button></figure>)}</div></section>}

function CategoryEditor(p:Shared){const [v,setV]=useState<Partial<Category>>({active:true,sortOrder:p.workspace.categories.length});return <section className="admin-subsection"><h2>{tx(p.locale,'หมวดหมู่','Categories')}</h2><form className="inline-admin-form" onSubmit={e=>{e.preventDefault();run(p,()=>p.api.adminSaveCategory(p.token,v),tx(p.locale,'บันทึกหมวดหมู่แล้ว','Category saved')).then(saved=>{if(saved)setV({active:true})})}}><input required placeholder="ชื่อไทย" value={v.nameTh||''} onChange={e=>setV({...v,nameTh:e.target.value})}/><input placeholder="English" value={v.nameEn||''} onChange={e=>setV({...v,nameEn:e.target.value})}/><button className="secondary-button">+</button></form><div className="chip-list">{p.workspace.categories.map(c=><button key={c.id} onClick={()=>setV(c)}>{tx(p.locale,c.nameTh,c.nameEn)}</button>)}</div></section>}

export function ContentAdmin(p:Shared){return <div><Header title={tx(p.locale,'ประกาศ Pre-order และบัญชีรับเงิน','Announcements, pre-orders and accounts')} sub={tx(p.locale,'จัดการข้อมูลที่แสดงหน้าร้านและขั้นตอนรับเงิน','Manage storefront content and payment destinations.')} /><AnnouncementEditor {...p}/><CampaignEditor {...p}/><AccountEditor {...p}/><ReviewModeration {...p}/><StatusEditor {...p}/></div>}
function AnnouncementEditor(p:Shared){const [v,setV]=useState<Partial<Announcement>>({active:true,kind:'GENERAL',contentEnabled:false,content:[],productIds:[]});const activityWork=async(label:string,work:()=>Promise<unknown>)=>{const id=p.activity.begin(label);try{const result=await work();p.activity.success(id);return result}catch(e){p.activity.failure(id,e instanceof Error?e.message:'Upload failed');throw e}};return <Simple title={tx(p.locale,'ประกาศ','Announcements')}><form className="admin-form" onSubmit={e=>{e.preventDefault();void run(p,()=>p.api.adminSaveAnnouncement(p.token,v),tx(p.locale,'บันทึกประกาศแล้ว','Announcement saved')).then(()=>setV({active:true,kind:'GENERAL',contentEnabled:false,content:[],productIds:[]}))}}><div className="form-grid"><Field label="หัวข้อไทย"><input required value={v.headerTh||''} onChange={e=>setV({...v,headerTh:e.target.value})}/></Field><Field label="English header"><input value={v.headerEn||''} onChange={e=>setV({...v,headerEn:e.target.value})}/></Field><Field label="Type"><select value={v.kind} onChange={e=>setV({...v,kind:e.target.value as Announcement['kind']})}><option>GENERAL</option><option>NEW_PRODUCT</option><option>PREORDER</option></select></Field></div><Field label={tx(p.locale,'ข้อความย่อสำหรับสไลด์','Slideshow summary')}><textarea value={v.bodyTh||''} onChange={e=>setV({...v,bodyTh:e.target.value})}/></Field><ImageUploader p={p} kind="ANNOUNCEMENT_IMAGE" values={v.imageUrl?[v.imageUrl]:[]} onChange={images=>setV({...v,imageUrl:images[0]||''})}/><Check label={tx(p.locale,'เขียนประกาศฉบับเต็มแบบ Blog','Enable full announcement story')} checked={Boolean(v.contentEnabled)} set={contentEnabled=>setV({...v,contentEnabled})}/>{v.contentEnabled&&<RichContentEditor blocks={v.content||[]} onChange={content=>setV({...v,content})} locale={p.locale} api={p.api} token={p.token} onActivity={activityWork}/>}<fieldset className="product-reference"><legend>{tx(p.locale,'สินค้าที่อ้างอิงในประกาศ','Products referenced by this announcement')}</legend><div>{p.workspace.products.map(product=><label key={product.id}><input type="checkbox" checked={(v.productIds||[]).includes(product.id)} onChange={e=>setV({...v,productIds:e.target.checked?[...(v.productIds||[]),product.id]:(v.productIds||[]).filter(id=>id!==product.id)})}/><MediaImage src={product.imageUrls[0]} alt=""/><span>{tx(p.locale,product.titleTh,product.titleEn)}</span></label>)}</div></fieldset><button className="secondary-button">{tx(p.locale,'บันทึกประกาศ','Save announcement')}</button></form><div className="chip-list">{p.workspace.announcements.map(a=><button key={a.id} onClick={()=>setV(a)}>{tx(p.locale,a.headerTh,a.headerEn)}</button>)}</div></Simple>}
function CampaignEditor(p:Shared){const [v,setV]=useState<Partial<PreorderCampaign>>({status:'DRAFT',purchaseLimit:1,capacity:1,deposit:0,terms:{id:'',version:1,titleTh:'เงื่อนไข Pre-order',titleEn:'Pre-order terms',bodyTh:'',bodyEn:''}});return <Simple title="Pre-order"><form className="admin-form" onSubmit={e=>{e.preventDefault();run(p,()=>p.api.adminSaveCampaign(p.token,v),tx(p.locale,'บันทึกรอบ Pre-order แล้ว','Pre-order saved'))}}><div className="form-grid"><Field label="ชื่อรอบไทย"><input required value={v.nameTh||''} onChange={e=>setV({...v,nameTh:e.target.value})}/></Field><Field label="English"><input value={v.nameEn||''} onChange={e=>setV({...v,nameEn:e.target.value})}/></Field><Field label={tx(p.locale,'เปิดรับ','Opens')}><input type="datetime-local" required value={local(v.openAt)} onChange={e=>setV({...v,openAt:new Date(e.target.value).toISOString()})}/></Field><Field label={tx(p.locale,'ปิดรับ','Closes')}><input type="datetime-local" required value={local(v.closeAt)} onChange={e=>setV({...v,closeAt:new Date(e.target.value).toISOString()})}/></Field><Field label={tx(p.locale,'คาดว่าถึง','Expected arrival')}><input type="date" value={v.expectedArrival?.slice(0,10)||''} onChange={e=>setV({...v,expectedArrival:new Date(e.target.value).toISOString()})}/></Field><Num label={tx(p.locale,'จำนวนรับ','Capacity')} value={v.capacity||0} set={n=>setV({...v,capacity:n})}/><Field label={tx(p.locale,'ชำระยอดคงเหลือเมื่อ','Final payment trigger')}><input value={v.finalPaymentTrigger||''} onChange={e=>setV({...v,finalPaymentTrigger:e.target.value})}/></Field><Field label="Status"><select value={v.status} onChange={e=>setV({...v,status:e.target.value as PreorderCampaign['status']})}><option>DRAFT</option><option>OPEN</option><option>CLOSED</option><option>CANCELLED</option></select></Field></div><Field label={tx(p.locale,'เงื่อนไขไทย','Thai terms')}><textarea value={v.terms?.bodyTh||''} onChange={e=>setV({...v,terms:{...v.terms!,bodyTh:e.target.value}})}/></Field><button className="secondary-button">{tx(p.locale,'บันทึกรอบ','Save campaign')}</button></form><div className="chip-list">{p.workspace.campaigns.map(c=><button key={c.id} onClick={()=>setV(c)}>{tx(p.locale,c.nameTh,c.nameEn)}</button>)}</div></Simple>}
function AccountEditor(p:Shared){const [v,setV]=useState<Partial<PaymentAccount>&{accountNumber?:string}>({active:true});return <Simple title={tx(p.locale,'บัญชีรับเงิน','Payment accounts')}><form className="inline-admin-form" onSubmit={e=>{e.preventDefault();run(p,()=>p.api.adminSavePaymentAccount(p.token,v),tx(p.locale,'บันทึกบัญชีแล้ว','Account saved')).then(saved=>{if(saved)setV({active:true})})}}><input required placeholder={tx(p.locale,'ธนาคาร/ช่องทาง','Bank/channel')} value={v.bankName||''} onChange={e=>setV({...v,bankName:e.target.value})}/><input required placeholder={tx(p.locale,'เลขบัญชี','Account number')} value={v.accountNumber||''} onChange={e=>setV({...v,accountNumber:e.target.value})}/><input placeholder={tx(p.locale,'ชื่อบัญชี','Account name')} value={v.accountName||''} onChange={e=>setV({...v,accountName:e.target.value})}/><button className="secondary-button">+</button></form><div className="chip-list">{p.workspace.paymentAccounts.map(a=><button key={a.id} onClick={()=>setV(a)}>{a.bankName} · {a.accountNumberMasked}</button>)}</div></Simple>}
function StatusEditor(p:Shared){const [rows,setRows]=useState(p.workspace.statuses);return <Simple title={tx(p.locale,'สถานะออเดอร์','Order statuses')}><div className="status-editor">{rows.map((s,i)=><div key={i}><input value={s.id} onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,id:e.target.value}:r))}/><input value={s.th} onChange={e=>setRows(rows.map((r,j)=>j===i?{...r,th:e.target.value}:r))}/><button onClick={()=>setRows(rows.filter((_,j)=>j!==i))}>×</button></div>)}<button className="secondary-button" onClick={()=>setRows([...rows,{id:'CUSTOM_'+Date.now(),th:'สถานะใหม่',en:'New status'}])}>+ {tx(p.locale,'เพิ่มสถานะ','Add status')}</button><button className="primary-button" onClick={()=>run(p,()=>p.api.adminSaveStatuses(p.token,rows),tx(p.locale,'บันทึกสถานะแล้ว','Statuses saved'))}>{tx(p.locale,'บันทึกสถานะ','Save statuses')}</button></div></Simple>}
function ReviewModeration(p:Shared){const [replies,setReplies]=useState<Record<string,string>>({});return <Simple title={tx(p.locale,'ตรวจรีวิวสินค้า','Review moderation')}><div className="review-moderation">{p.workspace.reviews.length===0?<p>{tx(p.locale,'ยังไม่มีรีวิว','No reviews yet')}</p>:p.workspace.reviews.map(r=><article key={r.id}><div><strong>{'★'.repeat(r.rating)} · {r.status}</strong><p>{r.body}</p></div><input placeholder={tx(p.locale,'คำตอบจากร้าน (ไม่บังคับ)','Store reply (optional)')} value={replies[r.id]??r.adminReply??''} onChange={e=>setReplies({...replies,[r.id]:e.target.value})}/><div><button className="secondary-button" onClick={()=>run(p,()=>p.api.adminModerateReview(p.token,r.id,true,replies[r.id]??r.adminReply??''),tx(p.locale,'อนุมัติรีวิวแล้ว','Review approved'))}>{tx(p.locale,'อนุมัติ','Approve')}</button><button className="secondary-button" onClick={()=>run(p,()=>p.api.adminModerateReview(p.token,r.id,false,replies[r.id]??''),tx(p.locale,'ซ่อนรีวิวแล้ว','Review hidden'))}>{tx(p.locale,'ซ่อน','Hide')}</button></div></article>)}</div></Simple>}

const Header=({title,sub}:{title:string;sub:string})=><div className="section-heading"><div><h1>{title}</h1><p>{sub}</p></div></div>
const Simple=({title,children}:{title:string;children:React.ReactNode})=><section className="admin-subsection"><h2>{title}</h2>{children}</section>
const Num=({label,value,set}:{label:string;value:number;set:(n:number)=>void})=><Field label={label}><input type="number" min="0" value={value} onChange={e=>set(Number(e.target.value))}/></Field>
const Check=({label,checked,set}:{label:string;checked:boolean;set:(v:boolean)=>void})=><label className="toggle-row"><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/></label>
const local=(v?:string)=>v?new Date(new Date(v).getTime()-new Date(v).getTimezoneOffset()*60000).toISOString().slice(0,16):''
