import { useEffect, useMemo, useState } from 'react'
import { CheckCircle, Minus, Plus, Timer, UploadSimple, WarningCircle } from '@phosphor-icons/react'
import type { ApiClient } from '../api/client'
import { cartTotal, formatCountdown, secondsRemaining, shippingTotal } from '../domain/logic'
import type { CartLine, Locale, OrderSummary, ProductType, Route, SessionInfo, StorefrontData } from '../domain/types'

const text = (locale: Locale, th: string, en: string) => locale === 'th' ? th : en
export function CartPage({ data, locale, online, carts, activeType, setActiveType, updateQuantity, reserve }: { data: StorefrontData; locale: Locale; online: boolean; carts: Record<ProductType, CartLine[]>; activeType: ProductType; setActiveType: (v: ProductType) => void; updateQuantity: (type: ProductType, productId: string, quantity: number) => void; reserve: (type: ProductType, terms?: { termsId: string; version: number }) => Promise<void> }) {
  const [accepted, setAccepted] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const lines = carts[activeType]; const products = lines.map((line) => ({ line, product: data.products.find((item) => item.id === line.productId)! })).filter((item) => item.product)
  const campaign = activeType === 'PREORDER' ? data.campaigns.find((item) => item.id === products[0]?.product.preorderCampaignId) : undefined
  const due = cartTotal(lines, data.products, activeType === 'PREORDER'); const full = cartTotal(lines, data.products)
  const shipping = shippingTotal(lines, data.products, data.settings)
  const submit = async () => { setBusy(true); setError(''); try { await reserve(activeType, campaign ? { termsId: campaign.terms.id, version: campaign.terms.version } : undefined) } catch (cause) { setError(cause instanceof Error ? cause.message : 'ยืนยันออเดอร์ไม่สำเร็จ') } finally { setBusy(false) } }
  return <div className="page narrow-page"><div className="section-heading"><div><h1>{text(locale, 'ตะกร้าของคุณ', 'Your cart')}</h1><p>{text(locale, 'สินค้าพร้อมส่งและ Pre-order แยกออเดอร์กัน', 'Ready stock and Pre-order are checked out separately.')}</p></div></div>
    <div className="segmented"><button className={activeType === 'READY' ? 'is-active' : ''} onClick={() => { setActiveType('READY'); setAccepted(false) }}>{text(locale, `พร้อมส่ง (${carts.READY.length})`, `Ready (${carts.READY.length})`)}</button><button className={activeType === 'PREORDER' ? 'is-active' : ''} onClick={() => { setActiveType('PREORDER'); setAccepted(false) }}>Pre-order ({carts.PREORDER.length})</button></div>
    {lines.length === 0 ? <div className="empty-state"><h2>{text(locale, 'ตะกร้านี้ยังว่าง', 'This cart is empty')}</h2><p>{text(locale, 'เพิ่มสินค้าที่ชอบแล้วกลับมาดูได้ที่นี่', 'Add something you like and return here.')}</p></div> : <>
      <div className="cart-list">{products.map(({ line, product }) => <article className="cart-line" key={line.productId}><div className="cart-thumb">{product.imageUrls[0] ? <img src={product.imageUrls[0]} alt="" /> : <span>1:1</span>}</div><div><strong>{text(locale, product.titleTh, product.titleEn)}</strong><span>฿{product.price.toLocaleString()} {data.settings.shippingMode === 'ITEM' && `· ${text(locale, 'ค่าส่ง', 'shipping')} ฿${product.shippingFee.toLocaleString()}/${text(locale, 'ชิ้น', 'unit')}`}</span></div><div className="stepper compact"><button onClick={() => updateQuantity(activeType, product.id, line.quantity - 1)} aria-label={text(locale, 'ลดจำนวน', 'Decrease')}><Minus /></button><output>{line.quantity}</output><button onClick={() => updateQuantity(activeType, product.id, line.quantity + 1)} aria-label={text(locale, 'เพิ่มจำนวน', 'Increase')}><Plus /></button></div></article>)}</div>
      {campaign && <section className="terms-panel"><div><strong>{text(locale, campaign.terms.titleTh, campaign.terms.titleEn)} · v{campaign.terms.version}</strong><span>{text(locale, `คาดว่าถึง ${new Date(campaign.expectedArrival).toLocaleDateString('th-TH')}`, `Expected ${new Date(campaign.expectedArrival).toLocaleDateString('en-US')}`)}</span></div><ol>{text(locale, campaign.terms.bodyTh, campaign.terms.bodyEn).split('\n').map((line) => <li key={line}>{line}</li>)}</ol><label className="check-row"><input type="checkbox" checked={accepted} onChange={(event) => setAccepted(event.target.checked)} /><span>{text(locale, 'ฉันอ่านและยอมรับเงื่อนไขฉบับนี้แล้ว', 'I have read and accept these terms.')}</span></label></section>}
      <section className="order-summary"><div><span>{text(locale, 'ยอดเต็ม', 'Full amount')}</span><strong>฿{full.toLocaleString()}</strong></div>{activeType === 'PREORDER' && <><div><span>{text(locale, 'มัดจำวันนี้', 'Deposit today')}</span><strong>฿{due.toLocaleString()}</strong></div><div><span>{text(locale, 'ยอดคงเหลือ', 'Balance')}</span><strong>฿{(full - due).toLocaleString()}</strong></div></>}<div><span>{text(locale, data.settings.shippingMode === 'ITEM' ? 'ค่าจัดส่งรวมตามสินค้า' : 'ค่าจัดส่งรวมตะกร้า', data.settings.shippingMode === 'ITEM' ? 'Item shipping total' : 'Cart shipping')}</span><strong>฿{shipping.toLocaleString()}</strong></div><div className="summary-total"><span>{text(locale, 'ชำระตอนนี้', 'Due now')}</span><strong>฿{(due + shipping).toLocaleString()}</strong></div></section>
      {!online && <div className="inline-alert warning"><WarningCircle /><span>{text(locale, 'ต้องออนไลน์ก่อนยืนยันเพื่อป้องกันสต็อกคลาดเคลื่อน', 'Go online before confirming so stock can be checked safely.')}</span></div>}{error && <p className="form-error" role="alert">{error}</p>}
      <button className="primary-button sticky-mobile-action" onClick={submit} disabled={busy || !online || Boolean(campaign && !accepted)}>{busy ? text(locale, 'กำลังพักสต็อก…', 'Reserving stock…') : text(locale, 'ยืนยันและเริ่มเวลา 20 นาที', 'Confirm and start 20-minute timer')}</button>
    </>}
  </div>
}

export function PaymentPage({ data, locale, online, order, api, session, demo, navigate }: { data: StorefrontData; locale: Locale; online: boolean; order: OrderSummary | null; api: ApiClient | null; session: SessionInfo | null; demo: boolean; navigate: (route: Route) => void }) {
  const [remaining, setRemaining] = useState(() => secondsRemaining(order?.reservedUntil)); const [file, setFile] = useState<File | null>(null); const [amount, setAmount] = useState(order?.balanceDue || 0); const [accountId, setAccountId] = useState(data.paymentAccounts[0]?.id || ''); const [busy, setBusy] = useState(false); const [success, setSuccess] = useState(false); const [error, setError] = useState('')
  useEffect(() => { const timer = window.setInterval(() => setRemaining(secondsRemaining(order?.reservedUntil)), 1000); return () => clearInterval(timer) }, [order?.reservedUntil])
  const account = useMemo(() => data.paymentAccounts.find((item) => item.id === accountId), [data.paymentAccounts, accountId])
  if (!order) return <div className="page narrow-page"><div className="empty-state"><h1>{text(locale, 'ไม่พบออเดอร์ที่กำลังชำระ', 'No pending payment')}</h1><button className="primary-button" onClick={() => navigate('cart')}>{text(locale, 'กลับไปที่ตะกร้า', 'Return to cart')}</button></div></div>
  const submit = async () => { if (!file && !demo) { setError(text(locale, 'กรุณาเลือกรูปสลิป', 'Choose a payment slip image')); return } setBusy(true); setError(''); try {
    if (!demo && api && session && file) { const base64 = await fileToBase64(file); await api.uploadSlip(session.token, { orderId: order.id, amount, accountId, transferAt: new Date().toISOString(), fileName: file.name, mimeType: file.type, base64 }) }
    await new Promise((resolve) => setTimeout(resolve, 500)); setSuccess(true)
  } catch (cause) { setError(cause instanceof Error ? cause.message : 'ส่งหลักฐานไม่สำเร็จ') } finally { setBusy(false) } }
  if (success) return <div className="page narrow-page"><div className="success-state"><CheckCircle size={58} weight="fill" /><h1>{text(locale, 'ส่งหลักฐานสำเร็จ', 'Payment proof submitted')}</h1><p>{text(locale, 'ออเดอร์ถูกบันทึกแล้ว กำลังรอแอดมินตรวจสอบ ส่วนอีเมลยืนยันอยู่ในคิวจัดส่ง', 'Your order is saved and awaiting review. The confirmation email is queued.')}</p><button className="primary-button" onClick={() => navigate('orders')}>{text(locale, 'ติดตามออเดอร์', 'Track order')}</button></div></div>
  return <div className="page narrow-page payment-page"><div className={`countdown ${remaining <= 300 ? 'is-urgent' : ''}`}><Timer size={24} /><span>{text(locale, 'ส่งหลักฐานภายใน', 'Submit proof within')}</span><strong>{formatCountdown(remaining)}</strong><small>{text(locale, 'ยึดเวลาจากเซิร์ฟเวอร์', 'Based on server time')}</small></div>
    {remaining <= 0 && <div className="inline-alert error"><WarningCircle /><span>{text(locale, 'หมดเวลาแล้ว ระบบกำลังคืนสต็อก กรุณาสร้างออเดอร์ใหม่', 'Time expired. Stock is being released; please create a new order.')}</span></div>}
    <section className="payment-card"><div><span>{text(locale, 'หมายเลขออเดอร์', 'Order reference')}</span><strong>{order.reference}</strong></div><div><span>{text(locale, 'ยอดที่ต้องโอน', 'Amount due')}</span><strong className="amount">฿{order.balanceDue.toLocaleString()}</strong></div></section>
    <label>{text(locale, 'บัญชีรับเงิน', 'Payment account')}</label><select value={accountId} onChange={(event) => setAccountId(event.target.value)}>{data.paymentAccounts.filter((item) => item.active).map((item) => <option key={item.id} value={item.id}>{item.bankName} · {item.accountNumberMasked}</option>)}</select>{account && <p className="helper-text">{account.accountName} · {account.accountNumberMasked}</p>}
    <label htmlFor="amount">{text(locale, 'ยอดที่โอน', 'Transferred amount')}</label><input id="amount" type="number" min="0" step="0.01" value={amount} onChange={(event) => setAmount(Number(event.target.value))} inputMode="decimal" />
    <label className="upload-zone" htmlFor="slip"><UploadSimple size={30} /><strong>{file ? file.name : text(locale, 'แตะเพื่อเลือกรูปสลิป', 'Choose a slip image')}</strong><span>{text(locale, 'JPG, PNG หรือ WebP ไม่เกิน 5MB', 'JPG, PNG or WebP up to 5MB')}</span><input id="slip" type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setFile(event.target.files?.[0] || null)} /></label>
    {!online && <div className="inline-alert warning"><WarningCircle /><span>{text(locale, 'เชื่อมต่ออินเทอร์เน็ตก่อนส่งหลักฐาน', 'Reconnect before submitting proof.')}</span></div>}{error && <p className="form-error" role="alert">{error}</p>}
    <button className="primary-button sticky-mobile-action" onClick={submit} disabled={busy || !online || remaining <= 0}>{busy ? text(locale, 'กำลังส่งหลักฐาน…', 'Submitting proof…') : text(locale, 'ส่งหลักฐานและยืนยัน', 'Submit proof and confirm')}</button>
  </div>
}

function fileToBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result).split(',')[1] || ''); reader.onerror = () => reject(new Error('อ่านไฟล์ไม่สำเร็จ')); reader.readAsDataURL(file) }) }
