import { useState } from 'react'
import { AlignCenterHorizontal,AlignLeft,AlignRight,Image,Plus,TextHOne,TextHTwo,TextHThree,TextT,Trash } from '@phosphor-icons/react'
import type { ApiClient } from '../api/client'
import type { Locale,RichBlock } from '../domain/types'
import { prepareImage } from '../lib/images'
import { MediaImage } from './MediaImage'

const tx=(locale:Locale,th:string,en:string)=>locale==='th'?th:en
export function RichContent({blocks=[],locale}:{blocks?:RichBlock[];locale:Locale}){return <article className="rich-content">{blocks.map(block=>{if(block.type==='image')return <figure key={block.id} data-align={block.align}><MediaImage src={block.imageRef} alt=""/></figure>;const Tag=block.type;return <Tag key={block.id} style={{textAlign:block.align}}>{tx(locale,block.textTh||'',block.textEn||'')}</Tag>})}</article>}

export function RichContentEditor({blocks,onChange,locale,api,token,onActivity}:{blocks:RichBlock[];onChange:(v:RichBlock[])=>void;locale:Locale;api:ApiClient;token:string;onActivity?:(label:string,work:()=>Promise<unknown>)=>Promise<unknown>}){
  const [uploading,setUploading]=useState(false)
  const add=(type:RichBlock['type'])=>onChange([...blocks,{id:crypto.randomUUID(),type,align:'left',textTh:'',textEn:''}])
  const patch=(id:string,value:Partial<RichBlock>)=>onChange(blocks.map(block=>block.id===id?{...block,...value}:block))
  const upload=async(file:File)=>{setUploading(true);try{const prepared=await prepareImage(file);const work=()=>api.adminUploadMedia(token,{kind:'BLOG_IMAGE',fileName:prepared.fileName,mimeType:prepared.mimeType,base64:prepared.base64});const saved=onActivity?await onActivity(tx(locale,'กำลังอัปโหลดรูปบทความ','Uploading article image'),work) as {ref:string}:await work();onChange([...blocks,{id:crypto.randomUUID(),type:'image',align:'center',imageRef:saved.ref}])}finally{setUploading(false)}}
  const alignLabel=(align:RichBlock['align'])=>align==='left'?tx(locale,'ชิดซ้าย','Align left'):align==='center'?tx(locale,'กึ่งกลาง','Align center'):tx(locale,'ชิดขวา','Align right')
  return <div className="rich-editor"><div className="rich-toolbar" aria-label={tx(locale,'เพิ่มส่วนเนื้อหา','Add content block')}><button type="button" onClick={()=>add('p')}><TextT/>{tx(locale,'ข้อความ','Text')}</button><button type="button" onClick={()=>add('h1')}><TextHOne/>H1</button><button type="button" onClick={()=>add('h2')}><TextHTwo/>H2</button><button type="button" onClick={()=>add('h3')}><TextHThree/>H3</button><label className={uploading?'is-busy':''}><Image/>{uploading?tx(locale,'กำลังอัปโหลด','Uploading'):tx(locale,'รูปภาพ','Image')}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div>{blocks.length===0&&<div className="rich-empty"><Plus/><span>{tx(locale,'เพิ่มหัวข้อ ข้อความ หรือรูปเพื่อเริ่มเขียน','Add a heading, paragraph, or image to begin')}</span></div>}{blocks.map((block,index)=><section className="rich-block" key={block.id}><div className="rich-block-head"><span>{block.type.toUpperCase()} · {index+1} · <b>{alignLabel(block.align)}</b></span><div className="alignment-actions" role="group" aria-label={tx(locale,'การจัดตำแหน่ง','Alignment')}><button type="button" className={block.align==='left'?'is-active':''} aria-pressed={block.align==='left'} aria-label={alignLabel('left')} title={alignLabel('left')} onClick={()=>patch(block.id,{align:'left'})}><AlignLeft/></button><button type="button" className={block.align==='center'?'is-active':''} aria-pressed={block.align==='center'} aria-label={alignLabel('center')} title={alignLabel('center')} onClick={()=>patch(block.id,{align:'center'})}><AlignCenterHorizontal/></button><button type="button" className={block.align==='right'?'is-active':''} aria-pressed={block.align==='right'} aria-label={alignLabel('right')} title={alignLabel('right')} onClick={()=>patch(block.id,{align:'right'})}><AlignRight/></button><button type="button" className="delete-block" aria-label={tx(locale,'ลบบล็อก','Delete block')} onClick={()=>onChange(blocks.filter(x=>x.id!==block.id))}><Trash/></button></div></div>{block.type==='image'?<MediaImage src={block.imageRef} alt=""/>:<><textarea aria-label="ภาษาไทย" placeholder="เนื้อหาภาษาไทย" value={block.textTh||''} style={{textAlign:block.align}} onChange={e=>patch(block.id,{textTh:e.target.value})}/><textarea aria-label="English" placeholder="English content" value={block.textEn||''} style={{textAlign:block.align}} onChange={e=>patch(block.id,{textEn:e.target.value})}/></>}</section>)}</div>
}
