var ORDER_TRANSITIONS = {
  PAYMENT_REVIEW: ['PAYMENT_CONFIRMED','PAYMENT_REJECTED'],
  PAYMENT_CONFIRMED: ['SELLER_PROCESSING'],
  SELLER_PROCESSING: ['SELLER_PREPARING_SHIPMENT','SELLER_SHIPPED'],
  SELLER_PREPARING_SHIPMENT: ['SELLER_SHIPPED'],
  SELLER_SHIPPED: ['THAILAND_RETURN_BATCH'],
  THAILAND_RETURN_BATCH: ['RETURNED_TO_THAI'],
  RETURNED_TO_THAI: ['ARRIVING_SHOP_2_3_DAYS'],
  ARRIVING_SHOP_2_3_DAYS: ['SHOP_PREPARING_SHIPMENT'],
  SHOP_PREPARING_SHIPMENT: ['OUT_FOR_DELIVERY'],
  OUT_FOR_DELIVERY: ['COMPLETED'],
  PAYMENT_REJECTED: ['AWAITING_PAYMENT','CANCELLED']
};

function adminDashboard_(context) {
  var today = Utilities.formatDate(new Date(),'Asia/Bangkok','yyyy-MM-dd'); var orders=records_('Orders');
  return { pendingPayments: records_('Payments').filter(function(item){return item.status==='PENDING_REVIEW';}).length, ordersToday: orders.filter(function(item){return String(item.createdAt).slice(0,10)===today;}).length, lowStock: records_('Products').filter(function(item){return truthy_(item.active)&&Number(item.stockOnHand)<=3;}).length, failedJobs: records_('JobQueue').filter(function(item){return item.state==='FAILED';}).length, contextUserId: context.user.id };
}
function adminSaveProduct_(context,payload,requestId){var before=payload.id?findById_('Products',payload.id):null;var data={type:payload.type==='PREORDER'?'PREORDER':'READY',titleTh:String(payload.titleTh||'').trim(),titleEn:String(payload.titleEn||'').trim(),descriptionTh:String(payload.descriptionTh||''),descriptionEn:String(payload.descriptionEn||''),price:Number(payload.price||0),deposit:Number(payload.deposit||0),stockOnHand:Math.floor(Number(payload.stockOnHand||0)),purchaseLimit:Math.max(1,Math.floor(Number(payload.purchaseLimit||1))),points:Math.max(0,Math.floor(Number(payload.points||0))),active:payload.active!==false,reviewEnabled:payload.reviewEnabled!==false,imagesJson:JSON.stringify(payload.imageUrls||[]),categoryId:payload.categoryId||'',preorderCampaignId:payload.preorderCampaignId||''};if(!data.titleTh||data.price<0||data.stockOnHand<0)throw apiError_('VALIDATION_ERROR','กรุณาตรวจชื่อ ราคา และสต็อก');var next=before?update_('Products',before.id,data,payload.version):insert_('Products',Object.assign({id:payload.id||Utilities.getUuid()},data));audit_(context.user.id,before?'UPDATE_PRODUCT':'CREATE_PRODUCT','Products',next.id,before,next);saveMutation_(requestId,context.user.id,'adminSaveProduct',stripMeta_(next));return stripMeta_(next);}
function adminReviewPayment_(context,payload,requestId){return withScriptLock_(function(){var payment=findById_('Payments',payload.paymentId);if(!payment||payment.status!=='PENDING_REVIEW')throw apiError_('PAYMENT_NOT_PENDING','รายการชำระเงินนี้ถูกตรวจแล้ว');var order=findById_('Orders',payment.orderId);var approved=payload.approved===true;var nextPayment=update_('Payments',payment.id,{status:approved?'CONFIRMED':'REJECTED',reviewNote:String(payload.note||''),reviewedBy:context.user.id,reviewedAt:new Date().toISOString()});var nextOrder=update_('Orders',order.id,{status:approved?'PAYMENT_CONFIRMED':'PAYMENT_REJECTED'});insert_('OrderStatusHistory',{orderId:order.id,fromStatus:order.status,toStatus:nextOrder.status,note:String(payload.note||''),actorUserId:context.user.id});if(!approved&&payload.restoreStock===true)restoreCommittedStock_(order.id);var job=queueJob_('PAYMENT_REVIEWED',{orderId:order.id,userId:order.userId,approved:approved,note:String(payload.note||'')});audit_(context.user.id,'REVIEW_PAYMENT','Payments',payment.id,payment,nextPayment);var result={payment:stripMeta_(nextPayment),order:publicOrder_(nextOrder),emailJobId:job.id};saveMutation_(requestId,context.user.id,'adminReviewPayment',result);return result;});}
function adminTransitionOrder_(context,payload,requestId){var order=findById_('Orders',payload.orderId);if(!order)throw apiError_('ORDER_NOT_FOUND','ไม่พบออเดอร์');var allowed=ORDER_TRANSITIONS[order.status]||[];if(allowed.indexOf(payload.status)<0)throw apiError_('INVALID_TRANSITION','ไม่สามารถเปลี่ยนจาก '+order.status+' เป็น '+payload.status);var next=update_('Orders',order.id,{status:payload.status});insert_('OrderStatusHistory',{orderId:order.id,fromStatus:order.status,toStatus:payload.status,note:String(payload.note||''),actorUserId:context.user.id});var job=queueJob_('ORDER_STATUS_CHANGED',{orderId:order.id,userId:order.userId,status:payload.status,note:String(payload.note||'')});audit_(context.user.id,'TRANSITION_ORDER','Orders',order.id,order,next);var result={order:publicOrder_(next),emailJobId:job.id};saveMutation_(requestId,context.user.id,'adminTransitionOrder',result);return result;}
function adminSendMessage_(context,payload,requestId){var order=findById_('Orders',payload.orderId);if(!order)throw apiError_('ORDER_NOT_FOUND','ไม่พบออเดอร์');var message=insert_('OrderMessages',{orderId:order.id,campaignId:payload.campaignId||'',subjectTh:String(payload.subjectTh||'ข้อความจากร้าน'),subjectEn:String(payload.subjectEn||'Message from the shop'),bodyTh:String(payload.bodyTh||''),bodyEn:String(payload.bodyEn||''),sendEmail:payload.sendEmail!==false,createdBy:context.user.id});insert_('Notifications',{userId:order.userId,orderId:order.id,kind:'ORDER_MESSAGE',titleTh:message.subjectTh,titleEn:message.subjectEn,bodyTh:message.bodyTh,bodyEn:message.bodyEn,readAt:''});var job=payload.sendEmail!==false?queueJob_('ORDER_MESSAGE',{orderId:order.id,userId:order.userId,messageId:message.id}):null;audit_(context.user.id,'SEND_ORDER_MESSAGE','OrderMessages',message.id,null,message);var result={message:stripMeta_(message),emailJobId:job&&job.id};saveMutation_(requestId,context.user.id,'adminSendMessage',result);return result;}
function restoreCommittedStock_(orderId){findAll_('StockReservations','orderId',orderId).forEach(function(reservation){if(reservation.state==='COMMITTED'){var product=findById_('Products',reservation.productId);update_('Products',product.id,{stockOnHand:Number(product.stockOnHand)+Number(reservation.quantity)});update_('StockReservations',reservation.id,{state:'RESTORED'});}});}
function audit_(userId,action,entity,entityId,before,after){insert_('AuditLog',{actorUserId:userId,action:action,entity:entity,entityId:entityId,beforeJson:JSON.stringify(before||null),afterJson:JSON.stringify(after||null)});}
