var ORDER_TRANSITIONS = {
  PAYMENT_REVIEW: ['PAYMENT_CONFIRMED','PAYMENT_REJECTED'],
  PAYMENT_CONFIRMED: ['SELLER_PROCESSING'],
  SELLER_PROCESSING: ['SELLER_PREPARING_SHIPMENT','SELLER_SHIPPED'],
  SELLER_PREPARING_SHIPMENT: ['SELLER_SHIPPED'],
  SELLER_SHIPPED: ['THAILAND_RETURN_BATCH'],
  THAILAND_RETURN_BATCH: ['RETURNED_TO_THAI'],
  RETURNED_TO_THAI: ['ARRIVING_SHOP_2_3_DAYS'],
  ARRIVING_SHOP_2_3_DAYS: ['SHOP_PREPARING_SHIPMENT'],
  SHOP_PREPARING_SHIPMENT: ['OUT_FOR_DELIVERY'],
  OUT_FOR_DELIVERY: ['COMPLETED'],
  PAYMENT_REJECTED: ['AWAITING_PAYMENT','CANCELLED']
};

function adminDashboard_(context) {
  var today = Utilities.formatDate(new Date(),'Asia/Bangkok','yyyy-MM-dd'); var orders=records_('Orders');
  return { pendingPayments: records_('Payments').filter(function(item){return item.status==='PENDING_REVIEW';}).length, ordersToday: orders.filter(function(item){return String(item.createdAt).slice(0,10)===today;}).length, lowStock: records_('Products').filter(function(item){return truthy_(item.active)&&Number(item.stockOnHand)<=3;}).length, failedJobs: records_('JobQueue').filter(function(item){return item.state==='FAILED';}).length, contextUserId: context.user.id };
}
function adminSaveProduct_(context,payload,requestId){var before=payload.id?findById_('Products',payload.id):null;var data={type:payload.type==='PREORDER'?'PREORDER':'READY',titleTh:String(payload.titleTh||'').trim(),titleEn:String(payload.titleEn||'').trim(),descriptionTh:String(payload.descriptionTh||''),descriptionEn:String(payload.descriptionEn||''),price:Number(payload.price||0),shippingFee:Math.max(0,Number(payload.shippingFee||0)),deposit:Number(payload.deposit||0),stockOnHand:Math.floor(Number(payload.stockOnHand||0)),purchaseLimit:Math.max(1,Math.floor(Number(payload.purchaseLimit||1))),points:Math.max(0,Math.floor(Number(payload.points||0))),active:payload.active!==false,reviewEnabled:payload.reviewEnabled!==false,imagesJson:JSON.stringify(payload.imageUrls||[]),categoryId:payload.categoryId||'',preorderCampaignId:payload.preorderCampaignId||''};if(!data.titleTh||data.price<0||data.stockOnHand<0)throw apiError_('VALIDATION_ERROR','กรุณาตรวจชื่อ ราคา และสต็อก');var next=before?update_('Products',before.id,data,payload.version):insert_('Products',Object.assign({id:payload.id||Utilities.getUuid()},data));audit_(context.user.id,before?'UPDATE_PRODUCT':'CREATE_PRODUCT','Products',next.id,before,next);saveMutation_(requestId,context.user.id,'adminSaveProduct',stripMeta_(next));return stripMeta_(next);}

function adminConfiguration_(context) {
  var admins = records_('Users').filter(function(user) { return ['ADMIN','OWNER'].indexOf(user.role) >= 0; }).map(function(user) { return { id:user.id,email:user.email,displayName:user.displayName,role:user.role,status:user.status }; });
  return { settings: publicSettings_(), admins: admins, currentRole: context.user.role };
}
function adminSaveSettings_(context, payload) {
  var allowed = ['storeNameTh','storeNameEn','logoUrl','primaryColor','defaultTheme','allowUserTheme','pointsEnabled','reviewsEnabled','favoritesEnabled','reservationMinutes','shippingMode','cartShippingFee','pointsPerBaht','minimumRedeemPoints','maxRedeemPercent','loaderKickerTh','loaderKickerEn','loaderTitleTh','loaderTitleEn','loaderMessageTh','loaderMessageEn','loaderLogoUrl'];
  allowed.forEach(function(key) { if (payload[key] !== undefined) setSetting_(key, payload[key]); });
  setSetting_('shippingFee', Number(setting_('cartShippingFee', 50)));
  audit_(context.user.id,'UPDATE_SETTINGS','Settings','shop',null,payload);
  return publicSettings_();
}
function adminAddAdmin_(context, payload) {
  requireRole_(context, ['OWNER']); requirePrivileged_(context);
  var email = normalizeEmail_(payload.email); var user = findOne_('Users','email',email); var before = user;
  if (!user) user = insert_('Users',{email:email,displayName:String(payload.displayName||email.split('@')[0]).trim(),role:'ADMIN',status:'ACTIVE',locale:'th',pointsBalance:0});
  else if (user.role !== 'OWNER') user = update_('Users',user.id,{role:'ADMIN',status:'ACTIVE',displayName:String(payload.displayName||user.displayName||email.split('@')[0]).trim()});
  audit_(context.user.id,'ADD_ADMIN','Users',user.id,before,user); return { id:user.id,email:user.email,displayName:user.displayName,role:user.role,status:user.status };
}

function adminWorkspace_(context) {
  var users={}; records_('Users').forEach(function(user){users[user.id]=user;});
  var files={}; records_('FileRegistry').forEach(function(file){files[file.id]=file;});
  var payments=records_('Payments').sort(function(a,b){return String(b.createdAt).localeCompare(String(a.createdAt));}).map(function(payment){var file=files[payment.slipFileId];return Object.assign(stripMeta_(payment),{slipUrl:file&&file.driveFileId?'https://drive.google.com/open?id='+file.driveFileId:''});});
  var orders=records_('Orders').sort(function(a,b){return String(b.createdAt).localeCompare(String(a.createdAt));}).map(function(order){var user=users[order.userId]||{};return Object.assign(publicOrder_(order),{userEmail:user.email||'',shippingFee:Number(order.shippingFee||0),payment:payments.filter(function(payment){return payment.orderId===order.id;})[0]||null});});
  return { products:records_('Products').map(adminProduct_),categories:records_('Categories').map(stripMeta_),announcements:records_('Announcements').map(stripMeta_),campaigns:records_('PreorderCampaigns').map(function(item){var terms=findById_('PreorderTerms',item.termsId);return Object.assign(stripMeta_(item),{terms:terms?stripMeta_(terms):null});}),paymentAccounts:records_('PaymentAccounts').map(function(item){var copy=stripMeta_(item);copy.accountNumberMasked=copy.accountNumberMasked||copy.accountNumber;return copy;}),orders:orders,reviews:records_('Reviews').map(stripMeta_),statuses:setting_('orderStatuses',defaultOrderStatuses_()),contextRole:context.user.role};
}
function adminProduct_(item){return{id:item.id,type:item.type,titleTh:item.titleTh,titleEn:item.titleEn,descriptionTh:item.descriptionTh,descriptionEn:item.descriptionEn,price:Number(item.price||0),shippingFee:Number(item.shippingFee||0),deposit:Number(item.deposit||0),stockOnHand:Number(item.stockOnHand||0),reservedQuantity:availableQuantity_(item.id)===Number(item.stockOnHand||0)?0:Number(item.stockOnHand||0)-availableQuantity_(item.id),purchaseLimit:Number(item.purchaseLimit||1),points:Number(item.points||0),active:truthy_(item.active),reviewEnabled:truthy_(item.reviewEnabled),imageUrls:jsonArray_(item.imagesJson),categoryId:item.categoryId,preorderCampaignId:item.preorderCampaignId||undefined,version:Number(item.version||1)};}
function defaultOrderStatuses_(){return[{id:'AWAITING_PAYMENT',th:'รอส่งหลักฐานการชำระเงิน',en:'Awaiting payment proof'},{id:'PAYMENT_REVIEW',th:'รอตรวจสอบ',en:'Payment review'},{id:'PAYMENT_CONFIRMED',th:'ยืนยันการชำระเงิน',en:'Payment confirmed'},{id:'PAYMENT_REJECTED',th:'หลักฐานไม่ผ่านการตรวจสอบ',en:'Payment rejected'},{id:'SELLER_PROCESSING',th:'รอผู้ขายจัดส่ง',en:'Waiting for seller'},{id:'SELLER_PREPARING_SHIPMENT',th:'ผู้ขายเตรียมจัดส่ง',en:'Seller preparing shipment'},{id:'SELLER_SHIPPED',th:'ผู้ขายส่งของแล้ว',en:'Seller shipped'},{id:'THAILAND_RETURN_BATCH',th:'ได้รอบส่งกลับไทย',en:'Thailand return batch'},{id:'RETURNED_TO_THAI',th:'ส่งกลับไทยแล้ว',en:'Returned to Thailand'},{id:'ARRIVING_SHOP_2_3_DAYS',th:'รอของถึงร้าน 2-3 วัน',en:'Arriving shop in 2-3 days'},{id:'BALANCE_DUE',th:'รอชำระยอดคงเหลือ',en:'Balance payment due'},{id:'SHOP_PREPARING_SHIPMENT',th:'ร้านเตรียมจัดส่ง',en:'Shop preparing shipment'},{id:'OUT_FOR_DELIVERY',th:'กำลังจัดส่ง',en:'Out for delivery'},{id:'COMPLETED',th:'จัดส่งสำเร็จ',en:'Completed'}];}
function adminSaveCategory_(context,payload){var current=payload.id&&findById_('Categories',payload.id);var data={nameTh:String(payload.nameTh||'').trim(),nameEn:String(payload.nameEn||'').trim(),active:payload.active!==false,sortOrder:Number(payload.sortOrder||0)};if(!data.nameTh)throw apiError_('VALIDATION_ERROR','กรุณาระบุชื่อหมวดหมู่');var next=current?update_('Categories',current.id,data,payload.version):insert_('Categories',Object.assign({id:payload.id||Utilities.getUuid()},data));audit_(context.user.id,current?'UPDATE_CATEGORY':'CREATE_CATEGORY','Categories',next.id,current,next);return stripMeta_(next);}
function adminSaveAnnouncement_(context,payload){var current=payload.id&&findById_('Announcements',payload.id);var data={headerTh:String(payload.headerTh||'').trim(),headerEn:String(payload.headerEn||'').trim(),bodyTh:String(payload.bodyTh||''),bodyEn:String(payload.bodyEn||''),imageUrl:String(payload.imageUrl||''),kind:['GENERAL','NEW_PRODUCT','PREORDER'].indexOf(payload.kind)>=0?payload.kind:'GENERAL',active:payload.active!==false,sortOrder:Number(payload.sortOrder||0)};if(!data.headerTh)throw apiError_('VALIDATION_ERROR','กรุณาระบุหัวข้อประกาศ');var next=current?update_('Announcements',current.id,data,payload.version):insert_('Announcements',Object.assign({id:payload.id||Utilities.getUuid()},data));audit_(context.user.id,current?'UPDATE_ANNOUNCEMENT':'CREATE_ANNOUNCEMENT','Announcements',next.id,current,next);return stripMeta_(next);}
function adminSavePaymentAccount_(context,payload){var current=payload.id&&findById_('PaymentAccounts',payload.id);var number=String(payload.accountNumber||current&&current.accountNumber||'').replace(/\s/g,'');var masked=number.length>4?'XXX-X-X'+number.slice(-4)+'-X':number;var data={bankName:String(payload.bankName||'').trim(),accountName:String(payload.accountName||'').trim(),accountNumber:number,accountNumberMasked:masked,active:payload.active!==false,sortOrder:Number(payload.sortOrder||0)};if(!data.bankName||!number)throw apiError_('VALIDATION_ERROR','กรุณาระบุธนาคารและเลขบัญชี');var next=current?update_('PaymentAccounts',current.id,data,payload.version):insert_('PaymentAccounts',Object.assign({id:payload.id||Utilities.getUuid()},data));audit_(context.user.id,current?'UPDATE_PAYMENT_ACCOUNT':'CREATE_PAYMENT_ACCOUNT','PaymentAccounts',next.id,current,next);return stripMeta_(next);}
function adminSaveCampaign_(context,payload){var current=payload.id&&findById_('PreorderCampaigns',payload.id);var id=current?current.id:(payload.id||Utilities.getUuid());var terms=current&&findById_('PreorderTerms',current.termsId);var termsData={campaignId:id,versionNumber:terms?Number(terms.versionNumber||1)+1:1,titleTh:String(payload.terms&&payload.terms.titleTh||'เงื่อนไข Pre-order'),titleEn:String(payload.terms&&payload.terms.titleEn||'Pre-order terms'),bodyTh:String(payload.terms&&payload.terms.bodyTh||''),bodyEn:String(payload.terms&&payload.terms.bodyEn||''),effectiveAt:new Date().toISOString(),createdBy:context.user.id};var nextTerms=terms?update_('PreorderTerms',terms.id,termsData):insert_('PreorderTerms',Object.assign({id:Utilities.getUuid()},termsData));var data={nameTh:String(payload.nameTh||'').trim(),nameEn:String(payload.nameEn||'').trim(),openAt:payload.openAt,closeAt:payload.closeAt,expectedArrival:payload.expectedArrival,capacity:Number(payload.capacity||0),purchaseLimit:Number(payload.purchaseLimit||1),deposit:Number(payload.deposit||0),finalPaymentTrigger:String(payload.finalPaymentTrigger||''),termsId:nextTerms.id,status:payload.status||'DRAFT'};if(!data.nameTh||!data.openAt||!data.closeAt)throw apiError_('VALIDATION_ERROR','กรุณากรอกชื่อและช่วงเวลา Pre-order');var next=current?update_('PreorderCampaigns',id,data,payload.version):insert_('PreorderCampaigns',Object.assign({id:id},data));audit_(context.user.id,current?'UPDATE_CAMPAIGN':'CREATE_CAMPAIGN','PreorderCampaigns',id,current,next);return stripMeta_(next);}
function adminSetEntityActive_(context,payload){var table={product:'Products',category:'Categories',announcement:'Announcements',account:'PaymentAccounts'}[payload.entity];if(!table)throw apiError_('BAD_REQUEST','ชนิดข้อมูลไม่ถูกต้อง');var before=findById_(table,payload.id);var next=update_(table,payload.id,{active:payload.active===true});audit_(context.user.id,'SET_ACTIVE',table,payload.id,before,next);return stripMeta_(next);}
function adminSaveStatuses_(context,payload){var statuses=payload.statuses||[];if(!Array.isArray(statuses)||!statuses.length)throw apiError_('VALIDATION_ERROR','ต้องมีอย่างน้อยหนึ่งสถานะ');setSetting_('orderStatuses',statuses);audit_(context.user.id,'UPDATE_STATUSES','Settings','orderStatuses',null,statuses);return statuses;}
function adminModerateReview_(context,payload){var review=findById_('Reviews',payload.id);if(!review)throw apiError_('NOT_FOUND','ไม่พบรีวิว');var next=update_('Reviews',review.id,{status:payload.approved===true?'APPROVED':'REJECTED',adminReply:String(payload.adminReply||'')});audit_(context.user.id,'MODERATE_REVIEW','Reviews',review.id,review,next);return stripMeta_(next);}
function adminReviewPayment_(context,payload,requestId){return withScriptLock_(function(){var payment=findById_('Payments',payload.paymentId);if(!payment||payment.status!=='PENDING_REVIEW')throw apiError_('PAYMENT_NOT_PENDING','รายการชำระเงินนี้ถูกตรวจแล้ว');var order=findById_('Orders',payment.orderId);var approved=payload.approved===true;var nextPayment=update_('Payments',payment.id,{status:approved?'CONFIRMED':'REJECTED',reviewNote:String(payload.note||''),reviewedBy:context.user.id,reviewedAt:new Date().toISOString()});var orderPatch={status:approved?'PAYMENT_CONFIRMED':'PAYMENT_REJECTED'};if(approved)orderPatch.totalPaid=Number(order.totalPaid||0)+Number(payment.amount||0);var nextOrder=update_('Orders',order.id,orderPatch);insert_('OrderStatusHistory',{orderId:order.id,fromStatus:order.status,toStatus:nextOrder.status,note:String(payload.note||''),actorUserId:context.user.id});insert_('Notifications',{userId:order.userId,orderId:order.id,kind:'PAYMENT_REVIEWED',titleTh:approved?'ยืนยันการชำระเงินแล้ว':'หลักฐานการชำระเงินไม่ผ่าน',titleEn:approved?'Payment confirmed':'Payment proof rejected',bodyTh:String(payload.note||order.reference),bodyEn:String(payload.note||order.reference),readAt:''});if(!approved&&payload.restoreStock===true)restoreCommittedStock_(order.id);var job=queueJob_('PAYMENT_REVIEWED',{orderId:order.id,userId:order.userId,approved:approved,note:String(payload.note||'')});audit_(context.user.id,'REVIEW_PAYMENT','Payments',payment.id,payment,nextPayment);var result={payment:stripMeta_(nextPayment),order:publicOrder_(nextOrder),emailJobId:job.id};saveMutation_(requestId,context.user.id,'adminReviewPayment',result);return result;});}
function adminTransitionOrder_(context,payload,requestId){var order=findById_('Orders',payload.orderId);if(!order)throw apiError_('ORDER_NOT_FOUND','ไม่พบออเดอร์');var statuses=setting_('orderStatuses',defaultOrderStatuses_());var configured=statuses.map(function(item){return item.id;});if(configured.indexOf(payload.status)<0)throw apiError_('INVALID_STATUS','ไม่พบสถานะที่เลือก');var updates={status:payload.status};if(payload.status==='BALANCE_DUE'){updates.reservedUntil=new Date(Date.now()+Number(setting_('reservationMinutes',20))*60000).toISOString();updates.amountDueNow=Math.max(0,Number(order.balanceDue||0)-Number(order.totalPaid||0));}var next=update_('Orders',order.id,updates);insert_('OrderStatusHistory',{orderId:order.id,fromStatus:order.status,toStatus:payload.status,note:String(payload.note||''),actorUserId:context.user.id});var label=statuses.filter(function(item){return item.id===payload.status;})[0]||{th:payload.status,en:payload.status};insert_('Notifications',{userId:order.userId,orderId:order.id,kind:'ORDER_STATUS',titleTh:'อัปเดตสถานะ: '+label.th,titleEn:'Status updated: '+label.en,bodyTh:String(payload.note||order.reference),bodyEn:String(payload.note||order.reference),readAt:''});var alreadyEarned=records_('PointsLedger').some(function(item){return item.orderId===order.id&&item.kind==='EARN';});if(payload.status==='COMPLETED'&&truthy_(setting_('pointsEnabled',true))&&!alreadyEarned){var earned=records_('OrderItems').filter(function(item){return item.orderId===order.id;}).reduce(function(sum,item){return sum+Number(item.pointsUnit||0)*Number(item.quantity||0);},0);if(earned>0){var user=findById_('Users',order.userId);update_('Users',user.id,{pointsBalance:Number(user.pointsBalance||0)+earned});insert_('PointsLedger',{userId:user.id,orderId:order.id,kind:'EARN',points:earned,expiresAt:'',note:'Completed order'});insert_('Notifications',{userId:user.id,orderId:order.id,kind:'POINTS_EARNED',titleTh:'ได้รับ '+earned+' แต้ม',titleEn:'You earned '+earned+' points',bodyTh:'แต้มจากออเดอร์ '+order.reference,bodyEn:'Points from order '+order.reference,readAt:''});}}var job=queueJob_('ORDER_STATUS_CHANGED',{orderId:order.id,userId:order.userId,status:payload.status,note:String(payload.note||'')});audit_(context.user.id,'TRANSITION_ORDER','Orders',order.id,order,next);var result={order:publicOrder_(next),emailJobId:job.id};saveMutation_(requestId,context.user.id,'adminTransitionOrder',result);return result;}
function adminSendMessage_(context,payload,requestId){var order=findById_('Orders',payload.orderId);if(!order)throw apiError_('ORDER_NOT_FOUND','ไม่พบออเดอร์');var message=insert_('OrderMessages',{orderId:order.id,campaignId:payload.campaignId||'',subjectTh:String(payload.subjectTh||'ข้อความจากร้าน'),subjectEn:String(payload.subjectEn||'Message from the shop'),bodyTh:String(payload.bodyTh||''),bodyEn:String(payload.bodyEn||''),sendEmail:payload.sendEmail!==false,createdBy:context.user.id});insert_('Notifications',{userId:order.userId,orderId:order.id,kind:'ORDER_MESSAGE',titleTh:message.subjectTh,titleEn:message.subjectEn,bodyTh:message.bodyTh,bodyEn:message.bodyEn,readAt:''});var job=payload.sendEmail!==false?queueJob_('ORDER_MESSAGE',{orderId:order.id,userId:order.userId,messageId:message.id}):null;audit_(context.user.id,'SEND_ORDER_MESSAGE','OrderMessages',message.id,null,message);var result={message:stripMeta_(message),emailJobId:job&&job.id};saveMutation_(requestId,context.user.id,'adminSendMessage',result);return result;}
function restoreCommittedStock_(orderId){findAll_('StockReservations','orderId',orderId).forEach(function(reservation){if(reservation.state==='COMMITTED'){var product=findById_('Products',reservation.productId);update_('Products',product.id,{stockOnHand:Number(product.stockOnHand)+Number(reservation.quantity)});update_('StockReservations',reservation.id,{state:'RESTORED'});}});}
function audit_(userId,action,entity,entityId,before,after){insert_('AuditLog',{actorUserId:userId,action:action,entity:entity,entityId:entityId,beforeJson:JSON.stringify(before||null),afterJson:JSON.stringify(after||null)});}
