function createReservation_(context, payload, requestId) {
  var previous = mutationResult_(requestId, context.user.id); if (previous) return previous;
  var lines = payload.lines || []; if (!Array.isArray(lines) || !lines.length) throw apiError_('EMPTY_CART', 'ตะกร้าว่าง');
  var shipping=payload.shipping||{};if(!String(shipping.name||'').trim()||!String(shipping.phone||'').trim()||!String(shipping.address||'').trim())throw apiError_('SHIPPING_REQUIRED','กรุณากรอกข้อมูลจัดส่งให้ครบ');var shippingAgreement=payload.shippingAcceptance||{};var shippingTermsVersion=Number(setting_('shippingTermsVersion',1));if(Number(shippingAgreement.version)!==shippingTermsVersion)throw apiError_('SHIPPING_TERMS_REQUIRED','กรุณาอ่านและกดยอมรับเงื่อนไขการจัดส่งฉบับล่าสุด');var specialTypes=['NONE','REMOTE','TOURIST','ISLAND','OTHER'];shipping.specialAreaType=specialTypes.indexOf(String(shipping.specialAreaType||'NONE'))>=0?String(shipping.specialAreaType||'NONE'):'NONE';shipping.xAccount=String(shipping.xAccount||'').trim().replace(/^@/,'').slice(0,50);
  return withScriptLock_(function() {
    var duplicate = mutationResult_(requestId, context.user.id); if (duplicate) return duplicate;
    cleanupExpiredReservations_();
    var normalized = []; var orderType = ''; var subtotal = 0; var depositDue = 0;
    lines.forEach(function(line) {
      var product = findById_('Products', line.productId); var quantity = Math.floor(Number(line.quantity || 0));
      if (!product || !truthy_(product.active)) throw apiError_('PRODUCT_UNAVAILABLE', 'สินค้าบางรายการไม่พร้อมขาย', { productId: line.productId });
      if (!orderType) orderType = product.type; if (orderType !== product.type) throw apiError_('MIXED_CART', 'สินค้าพร้อมส่งและ Pre-order ต้องแยกออเดอร์');
      if (quantity < 1 || quantity > Number(product.purchaseLimit || 1)) throw apiError_('PURCHASE_LIMIT', 'จำนวนสินค้าเกินที่กำหนด', { productId: product.id, limit: Number(product.purchaseLimit || 1) });
      var purchased = purchasedQuantity_(context.user.id, product.id); if (purchased + quantity > Number(product.purchaseLimit || 1)) throw apiError_('CUSTOMER_LIMIT_REACHED', 'คุณซื้อสินค้านี้ครบจำนวนที่กำหนดแล้ว', { productId: product.id, remaining: Math.max(0, Number(product.purchaseLimit || 1) - purchased) });
      var available = availableQuantity_(product.id); if (quantity > available) throw apiError_('STOCK_CONFLICT', 'สินค้าเพิ่งถูกจองครบหรือเหลือน้อยกว่าที่เลือก', { productId: product.id, available: available });
      if (product.type === 'PREORDER') validatePreorder_(product, payload.termsAcceptance);
      normalized.push({ product: product, quantity: quantity }); subtotal += Number(product.price || 0) * quantity; depositDue += (product.type === 'PREORDER' ? Number(product.deposit || 0) : Number(product.price || 0)) * quantity;
    });
    var shippingMode = setting_('shippingMode', 'CART'); var shippingFee = shippingMode === 'ITEM' ? normalized.reduce(function(sum,item){return sum + Number(item.product.shippingFee || 0) * item.quantity;},0) : Number(setting_('cartShippingFee', setting_('shippingFee', 50)));var points=truthy_(setting_('pointsEnabled',true))?Math.floor(Number(payload.redeemPoints||0)):0;var minPoints=Number(setting_('minimumRedeemPoints',100));var perBaht=Number(setting_('pointsPerBaht',10));var maxDiscount=Math.floor(subtotal*Number(setting_('maxRedeemPercent',20))/100);if(points>0&&(points<minPoints||points>Number(context.user.pointsBalance||0)))throw apiError_('INVALID_POINTS','แต้มไม่เพียงพอหรือไม่ถึงขั้นต่ำ');var discount=Math.min(Math.floor(points/perBaht),maxDiscount);points=discount*perBaht; var amountDueNow = Math.max(0,depositDue + shippingFee-discount); var now = new Date(); var expiresAt = new Date(now.getTime() + Number(setting_('reservationMinutes', 20)) * 60000).toISOString(); var orderId = Utilities.getUuid(); var reference = reference_(orderType);
    var order = insert_('Orders', { id: orderId, reference: reference, userId: context.user.id, orderType: orderType, status: 'AWAITING_PAYMENT', subtotal: subtotal, shippingFee: shippingFee, shippingBaseFee:shippingFee,shippingAdjustment:0,shippingAdjustmentNote:'', amountDueNow: amountDueNow, totalPaid: 0, balanceDue: subtotal + shippingFee-discount, reservedUntil: expiresAt, shippingJson: JSON.stringify(shipping), termsVersion: payload.termsAcceptance && payload.termsAcceptance.version || '',shippingTermsVersion:shippingTermsVersion,shippingTermsAcceptedAt:now.toISOString(), paymentAccountId: '',pointsRedeemed:points,discount:discount });if(shipping.xAccount&&shipping.xAccount!==context.user.xAccount)update_('Users',context.user.id,{xAccount:shipping.xAccount});if(points>0){update_('Users',context.user.id,{pointsBalance:Number(context.user.pointsBalance||0)-points});insert_('PointsLedger',{userId:context.user.id,orderId:orderId,kind:'REDEEM',points:-points,expiresAt:'',note:'Order discount'});}
    normalized.forEach(function(item) {
      insert_('OrderItems', { orderId: orderId, productId: item.product.id, titleSnapshot: item.product.titleTh + ' / ' + item.product.titleEn, unitPrice: Number(item.product.price || 0), depositUnit: Number(item.product.deposit || 0), quantity: item.quantity, pointsUnit: Number(item.product.points || 0) });
      insert_('StockReservations', { orderId: orderId, productId: item.product.id, userId: context.user.id, quantity: item.quantity, state: 'HELD', expiresAt: expiresAt });
    });
    if (orderType === 'PREORDER') insert_('TermsAcceptances', { orderId: orderId, userId: context.user.id, termsId: payload.termsAcceptance.termsId, versionNumber: payload.termsAcceptance.version, acceptedAt: now.toISOString(), deviceInfo: String(payload.deviceInfo || '').slice(0, 250) });
    insert_('OrderStatusHistory', { orderId: orderId, fromStatus: '', toStatus: 'AWAITING_PAYMENT', note: 'Stock reserved for payment', actorUserId: context.user.id });
    var result = { order: publicOrder_(order), serverTime: new Date().toISOString() }; saveMutation_(requestId, context.user.id, 'createReservation', result); return result;
  });
}

function validatePreorder_(product, acceptance) {
  var campaign = findById_('PreorderCampaigns', product.preorderCampaignId); if (!campaign || computedCampaignStatus_(campaign) !== 'OPEN') throw apiError_('PREORDER_CLOSED', 'รอบ Pre-order ไม่ได้เปิดรับ');
  var terms = findById_('PreorderTerms', campaign.termsId); if (!terms || !acceptance || acceptance.termsId !== terms.id || Number(acceptance.version) !== Number(terms.versionNumber)) throw apiError_('TERMS_REQUIRED', 'กรุณาอ่านและยอมรับเงื่อนไข Pre-order ฉบับล่าสุด');
}
function purchasedQuantity_(userId, productId) {
  var validOrders = {}; records_('Orders').filter(function(order){return order.userId===userId && ['CANCELLED','EXPIRED','REFUNDED'].indexOf(order.status)<0;}).forEach(function(order){validOrders[order.id]=true;});
  return records_('OrderItems').filter(function(item){return validOrders[item.orderId] && item.productId===productId;}).reduce(function(sum,item){return sum+Number(item.quantity||0);},0);
}
function availableQuantity_(productId) {
  var product = findById_('Products', productId); if (!product) return 0; var held = records_('StockReservations').filter(function(item){return item.productId===productId && ['HELD','SUBMITTED'].indexOf(item.state)>=0 && new Date(item.expiresAt).getTime()>Date.now();}).reduce(function(sum,item){return sum+Number(item.quantity||0);},0); return Math.max(0, Number(product.stockOnHand||0)-held);
}
function reference_(type) { var date = Utilities.formatDate(new Date(), 'Asia/Bangkok', 'yyMMdd'); var suffix = String(Math.floor(1000 + Math.random()*9000)); return (type==='PREORDER'?'PO':'RD')+'-'+date+'-'+suffix; }

function uploadSlip_(context, payload, requestId) {
  var previous = mutationResult_(requestId, context.user.id); if (previous) return previous;
  var order = findById_('Orders', payload.orderId); if (!order || order.userId !== context.user.id) throw apiError_('ORDER_NOT_FOUND', 'ไม่พบออเดอร์');
  if (['AWAITING_PAYMENT','BALANCE_DUE'].indexOf(order.status)<0) throw apiError_('INVALID_ORDER_STATE', 'ออเดอร์นี้ไม่อยู่ในขั้นตอนส่งหลักฐาน');
  if (new Date(order.reservedUntil).getTime() <= Date.now()) { cleanupExpiredReservations_(); throw apiError_('RESERVATION_EXPIRED', 'หมดเวลาชำระแล้ว กรุณาสร้างออเดอร์ใหม่'); }
  var mime = String(payload.mimeType || ''); if (['image/jpeg','image/png','image/webp'].indexOf(mime)<0) throw apiError_('INVALID_FILE_TYPE', 'รองรับเฉพาะ JPG, PNG หรือ WebP');
  var bytes; try { bytes = Utilities.base64Decode(String(payload.base64 || '')); } catch (_) { throw apiError_('INVALID_FILE', 'อ่านไฟล์สลิปไม่สำเร็จ'); }
  if (!bytes.length || bytes.length > CONFIG.MAX_SLIP_BYTES) throw apiError_('FILE_TOO_LARGE', 'รูปสลิปต้องมีขนาดไม่เกิน 5MB');
  var folderId = PropertiesService.getScriptProperties().getProperty('PAYMENT_SLIPS_FOLDER_ID'); if (!folderId) { ensureDriveFolders_(); folderId = PropertiesService.getScriptProperties().getProperty('PAYMENT_SLIPS_FOLDER_ID'); }
  var safeName = String(payload.fileName || 'slip.jpg').replace(/[^A-Za-z0-9._-]/g,'_').slice(-100); var blob = Utilities.newBlob(bytes, mime, order.reference+'-'+safeName); var file = DriveApp.getFolderById(folderId).createFile(blob);
  try {
    return withScriptLock_(function() {
      var duplicate = mutationResult_(requestId, context.user.id); if (duplicate) { file.setTrashed(true); return duplicate; }
      var fresh = findById_('Orders', payload.orderId); if (!fresh || ['AWAITING_PAYMENT','BALANCE_DUE'].indexOf(fresh.status)<0 || new Date(fresh.reservedUntil).getTime() <= Date.now()) { file.setTrashed(true); cleanupExpiredReservations_(); throw apiError_('RESERVATION_EXPIRED', 'หมดเวลาชำระแล้ว กรุณาติดต่อร้านค้า'); }
      var fileRecord = insert_('FileRegistry', { ownerUserId: context.user.id, orderId: fresh.id, kind: 'PAYMENT_SLIP', driveFileId: file.getId(), fileName: safeName, mimeType: mime, size: bytes.length, checksum: digest_(Utilities.base64Encode(bytes)), state: 'ACTIVE' });
      var amount = Number(payload.amount || 0); if (amount <= 0) throw apiError_('INVALID_AMOUNT', 'กรุณาระบุยอดที่โอน');
      var isBalance=fresh.status==='BALANCE_DUE';var expected=isBalance?Math.max(0,Number(fresh.balanceDue||0)-Number(fresh.totalPaid||0)):Number(fresh.amountDueNow||0);if(Math.abs(amount-expected)>0.01)throw apiError_('AMOUNT_MISMATCH','ยอดโอนไม่ตรงกับยอดที่ต้องชำระ',{expected:expected});
      var payment = insert_('Payments', { orderId: fresh.id, userId: context.user.id, kind: isBalance?'BALANCE':(fresh.orderType==='PREORDER'?'DEPOSIT':'FULL'), amount: amount, accountId: payload.accountId, slipFileId: fileRecord.id, transferAt: payload.transferAt || new Date().toISOString(), status: 'PENDING_REVIEW', reviewNote: '', reviewedBy: '', reviewedAt: '' });
      if(!isBalance)findAll_('StockReservations','orderId',fresh.id).forEach(function(reservation){ if(reservation.state==='HELD'){ var product=findById_('Products',reservation.productId); if(!product || Number(product.stockOnHand)<Number(reservation.quantity))throw apiError_('STOCK_INVARIANT','สต็อกไม่เพียงพอระหว่างบันทึก'); update_('Products',product.id,{stockOnHand:Number(product.stockOnHand)-Number(reservation.quantity)}); update_('StockReservations',reservation.id,{state:'COMMITTED'}); } });
      var next = update_('Orders', fresh.id, { status:'PAYMENT_REVIEW', paymentAccountId:payload.accountId }); insert_('OrderStatusHistory',{orderId:fresh.id,fromStatus:fresh.status,toStatus:'PAYMENT_REVIEW',note:isBalance?'Balance payment proof submitted':'Payment proof submitted',actorUserId:context.user.id});
      var emailJob = queueJob_('ORDER_PAYMENT_SUBMITTED',{orderId:fresh.id,userId:context.user.id,paymentId:payment.id}); var result={order:publicOrder_(next),paymentId:payment.id,emailJobId:emailJob.id}; saveMutation_(requestId,context.user.id,'uploadSlip',result); return result;
    });
  } catch (error) { try { if (file && !file.isTrashed()) file.setTrashed(true); } catch (_) {} throw error; }
}

function cleanupExpiredReservations() { return cleanupExpiredReservations_(); }
function cleanupExpiredReservations_() {
  var now = Date.now(); var expired = records_('StockReservations').filter(function(item){return item.state==='HELD' && new Date(item.expiresAt).getTime()<=now;}); var orderIds={}; expired.forEach(function(item){update_('StockReservations',item.id,{state:'EXPIRED'});orderIds[item.orderId]=true;}); Object.keys(orderIds).forEach(function(orderId){var order=findById_('Orders',orderId);if(order&&order.status==='AWAITING_PAYMENT'){update_('Orders',order.id,{status:'EXPIRED'});if(Number(order.pointsRedeemed||0)>0){var user=findById_('Users',order.userId);update_('Users',user.id,{pointsBalance:Number(user.pointsBalance||0)+Number(order.pointsRedeemed)});insert_('PointsLedger',{userId:user.id,orderId:order.id,kind:'RESTORE',points:Number(order.pointsRedeemed),expiresAt:'',note:'Expired order'});}insert_('OrderStatusHistory',{orderId:order.id,fromStatus:'AWAITING_PAYMENT',toStatus:'EXPIRED',note:'Payment window expired',actorUserId:'SYSTEM'});queueJob_('ORDER_EXPIRED',{orderId:order.id,userId:order.userId});}}); return {released:expired.length};
}
function listOrders_(context) { return records_('Orders').filter(function(order){return order.userId===context.user.id;}).sort(function(a,b){return String(b.createdAt).localeCompare(String(a.createdAt));}).map(function(order){var result=publicOrder_(order);result.items=findAll_('OrderItems','orderId',order.id).map(stripMeta_);result.history=findAll_('OrderStatusHistory','orderId',order.id).sort(function(a,b){return String(a.createdAt).localeCompare(String(b.createdAt));}).map(stripMeta_);result.messages=findAll_('Notifications','orderId',order.id).filter(function(item){return ['ORDER_MESSAGE','ADMIN_MESSAGE'].indexOf(item.kind)>=0;}).map(stripMeta_);return result;}); }
function publicOrder_(order) { var remaining=Math.max(0,Number(order.balanceDue||0)-Number(order.totalPaid||0));var shipping={};try{shipping=JSON.parse(order.shippingJson||'{}');}catch(_){}return { id:order.id,reference:order.reference,orderType:order.orderType,status:order.status,subtotal:Number(order.subtotal||0),shippingFee:Number(order.shippingFee||0),shippingBaseFee:Number(order.shippingBaseFee||order.shippingFee||0),shippingAdjustment:Number(order.shippingAdjustment||0),shippingAdjustmentNote:order.shippingAdjustmentNote||'',amountDueNow:order.status==='BALANCE_DUE'?remaining:Number(order.amountDueNow||0),totalPaid:Number(order.totalPaid||0),balanceDue:remaining,shipping:shipping,reservedUntil:order.reservedUntil||undefined,createdAt:order.createdAt }; }
function listFavorites_(context){return records_('Favorites').filter(function(item){return item.userId===context.user.id&&truthy_(item.active);}).map(function(item){return item.productId;});}
function toggleFavorite_(context,productId,requestId){var product=findById_('Products',productId);if(!product)throw apiError_('PRODUCT_NOT_FOUND','ไม่พบสินค้า');var id=context.user.id+':'+productId;var current=findById_('Favorites',id);var active=current?!truthy_(current.active):true;current?update_('Favorites',id,{active:active}):insert_('Favorites',{id:id,userId:context.user.id,productId:productId,active:active});return{active:active,requestId:requestId};}
function productReviews_(productId){var users={};records_('Users').forEach(function(user){users[user.id]=user;});return records_('Reviews').filter(function(item){return item.productId===productId&&item.status==='APPROVED';}).map(function(item){return{id:item.id,rating:Number(item.rating),body:item.body,adminReply:item.adminReply||'',displayName:(users[item.userId]&&users[item.userId].displayName)||'Customer',createdAt:item.createdAt};});}
function createReview_(context,payload){if(!truthy_(setting_('reviewsEnabled',true)))throw apiError_('FEATURE_DISABLED','ปิดระบบรีวิวอยู่');var product=findById_('Products',payload.productId);if(!product||!truthy_(product.reviewEnabled))throw apiError_('REVIEW_DISABLED','สินค้านี้ไม่เปิดรีวิว');var completed={};records_('Orders').filter(function(order){return order.userId===context.user.id&&order.status==='COMPLETED';}).forEach(function(order){completed[order.id]=true;});var item=records_('OrderItems').filter(function(row){return completed[row.orderId]&&row.productId===payload.productId;})[0];if(!item)throw apiError_('NOT_PURCHASED','รีวิวได้หลังได้รับสินค้าแล้ว');var existing=records_('Reviews').filter(function(row){return row.userId===context.user.id&&row.productId===payload.productId;})[0];if(existing)throw apiError_('ALREADY_REVIEWED','คุณรีวิวสินค้านี้แล้ว');var rating=Math.max(1,Math.min(5,Math.floor(Number(payload.rating||0))));return stripMeta_(insert_('Reviews',{userId:context.user.id,productId:payload.productId,orderItemId:item.id,rating:rating,body:String(payload.body||'').slice(0,1000),status:'PENDING',adminReply:''}));}
function listNotifications_(context){return records_('Notifications').filter(function(item){return item.userId===context.user.id;}).sort(function(a,b){return String(b.createdAt).localeCompare(String(a.createdAt));}).slice(0,100).map(stripMeta_);}
function readNotification_(context,id){var item=findById_('Notifications',id);if(!item||item.userId!==context.user.id)throw apiError_('NOT_FOUND','ไม่พบการแจ้งเตือน');return stripMeta_(update_('Notifications',id,{readAt:new Date().toISOString()}));}
