function storefront_(locale) {
  cleanupExpiredReservations_();
  var activeReservations = records_('StockReservations').filter(function(item) { return ['HELD', 'SUBMITTED'].indexOf(item.state) >= 0 && new Date(item.expiresAt).getTime() > Date.now(); });
  var reservedByProduct = {}; activeReservations.forEach(function(item) { reservedByProduct[item.productId] = Number(reservedByProduct[item.productId] || 0) + Number(item.quantity || 0); });
  var products = records_('Products').filter(function(item) { return truthy_(item.active); }).map(function(item) { return { id: item.id, type: item.type, titleTh: item.titleTh, titleEn: item.titleEn, descriptionTh: item.descriptionTh, descriptionEn: item.descriptionEn, price: Number(item.price || 0), shippingFee: Number(item.shippingFee || 0), shippingCalculation:item.shippingCalculation==='FLAT'?'FLAT':'PER_UNIT', deposit: Number(item.deposit || 0), stockOnHand: Number(item.stockOnHand || 0), reservedQuantity: Number(reservedByProduct[item.id] || 0), purchaseLimit: Number(item.purchaseLimit || 1), points: Number(item.points || 0), active: truthy_(item.active), reviewEnabled: truthy_(item.reviewEnabled), imageUrls: jsonArray_(item.imagesJson), categoryId: item.categoryId, preorderCampaignId: item.preorderCampaignId || undefined,contentEnabled:truthy_(item.contentEnabled),content:jsonArray_(item.contentJson) }; });
  var campaigns = records_('PreorderCampaigns').filter(function(item) { return item.status !== 'DRAFT'; }).map(function(item) { var terms = findById_('PreorderTerms', item.termsId); return { id: item.id, nameTh: item.nameTh, nameEn: item.nameEn, openAt: item.openAt, closeAt: item.closeAt, expectedArrival: item.expectedArrival, capacity: Number(item.capacity || 0), reservedQuantity: campaignReserved_(item.id), purchaseLimit: Number(item.purchaseLimit || 1), deposit: Number(item.deposit || 0), finalPaymentTrigger: item.finalPaymentTrigger, status: computedCampaignStatus_(item), terms: terms ? { id: terms.id, version: Number(terms.versionNumber || 1), titleTh: terms.titleTh, titleEn: terms.titleEn, bodyTh: terms.bodyTh, bodyEn: terms.bodyEn } : null }; });
  return {
    settings: publicSettings_(),
    categories: records_('Categories').filter(function(item) { return truthy_(item.active); }).sort(function(a,b){return Number(a.sortOrder)-Number(b.sortOrder);}).map(stripMeta_),
    announcements: records_('Announcements').filter(function(item) { return truthy_(item.active); }).sort(function(a,b){return Number(a.sortOrder)-Number(b.sortOrder);}).map(function(item){var copy=stripMeta_(item);copy.contentEnabled=truthy_(item.contentEnabled);copy.content=jsonArray_(item.contentJson);copy.productIds=jsonArray_(item.productIdsJson);return copy;}),
    products: products, campaigns: campaigns,
    paymentAccounts: records_('PaymentAccounts').filter(function(item) { return truthy_(item.active); }).sort(function(a,b){return Number(a.sortOrder)-Number(b.sortOrder);}).map(function(item){return { id:item.id, bankName:item.bankName, accountName:item.accountName, accountNumberMasked:item.accountNumberMasked, active:true };}),
    serverTime: new Date().toISOString(), locale: locale
  };
}
function publicSettings_() { return { storeNameTh: setting_('storeNameTh', 'ร้านของฉัน'), storeNameEn: setting_('storeNameEn', 'My Shop'), logoUrl: setting_('logoUrl', ''), primaryColor: setting_('primaryColor', '#6d28d9'), defaultTheme: setting_('defaultTheme', 'system'), allowUserTheme: truthy_(setting_('allowUserTheme', true)), pointsEnabled: truthy_(setting_('pointsEnabled', true)), reviewsEnabled: truthy_(setting_('reviewsEnabled', true)), favoritesEnabled: truthy_(setting_('favoritesEnabled', true)), reservationMinutes: Number(setting_('reservationMinutes', 20)), currency: 'THB', shippingFee: Number(setting_('shippingFee', 50)), shippingMode: setting_('shippingMode', 'CART') === 'ITEM' ? 'ITEM' : 'CART', cartShippingFee: Number(setting_('cartShippingFee', setting_('shippingFee', 50))), shippingTermsTh:setting_('shippingTermsTh','ค่าจัดส่งที่แสดงเป็นราคาตั้งต้น พื้นที่พิเศษคิดเพิ่มตามจริง'),shippingTermsEn:setting_('shippingTermsEn','Displayed shipping is the base rate; special areas are charged at actual cost.'),shippingTermsVersion:Number(setting_('shippingTermsVersion',1)),remoteAreaTermsTh:setting_('remoteAreaTermsTh','พื้นที่ห่างไกล พื้นที่ท่องเที่ยว และเกาะ คิดค่าส่งเพิ่มตามจริง'),remoteAreaTermsEn:setting_('remoteAreaTermsEn','Remote, tourist, and island destinations are charged at actual cost.'),lowStockThreshold:Math.max(0,Number(setting_('lowStockThreshold',3))), pointsPerBaht:Number(setting_('pointsPerBaht',10)),minimumRedeemPoints:Number(setting_('minimumRedeemPoints',100)),maxRedeemPercent:Number(setting_('maxRedeemPercent',20)), loaderKickerTh: setting_('loaderKickerTh', 'ยินดีต้อนรับสู่'), loaderKickerEn: setting_('loaderKickerEn', 'Welcome to'), loaderTitleTh: setting_('loaderTitleTh', ''), loaderTitleEn: setting_('loaderTitleEn', ''), loaderMessageTh: setting_('loaderMessageTh', 'กำลังจัดชั้นสินค้าให้คุณ'), loaderMessageEn: setting_('loaderMessageEn', 'Curating the shelves for you'), loaderLogoUrl: setting_('loaderLogoUrl', '') }; }
function truthy_(value) { return value === true || value === 'TRUE' || value === 'true' || value === 1 || value === '1'; }
function jsonArray_(value) { try { var parsed = JSON.parse(value || '[]'); return Array.isArray(parsed) ? parsed : []; } catch (_) { return []; } }
function stripMeta_(record) { var copy = Object.assign({}, record); delete copy._row; delete copy.version; delete copy.createdAt; delete copy.updatedAt; return copy; }
function computedCampaignStatus_(campaign) { var now = Date.now(); if (campaign.status === 'CANCELLED') return 'CANCELLED'; if (campaignReserved_(campaign.id) >= Number(campaign.capacity || 0)) return 'FULL'; if (now < new Date(campaign.openAt).getTime()) return 'DRAFT'; if (now > new Date(campaign.closeAt).getTime()) return 'CLOSED'; return 'OPEN'; }
function campaignReserved_(campaignId) { var productIds = records_('Products').filter(function(item){return item.preorderCampaignId===campaignId;}).map(function(item){return item.id;}); return records_('StockReservations').filter(function(item){return productIds.indexOf(item.productId)>=0 && ['HELD','SUBMITTED','COMMITTED'].indexOf(item.state)>=0;}).reduce(function(sum,item){return sum+Number(item.quantity||0);},0); }
